// ─────────────────────────────────────────────────────────────
// ADAPTIVE WARM-UP VIEW (Tindeq-driven)
// ─────────────────────────────────────────────────────────────
// Walks the user through the warm-up protocol generated by
// src/model/warmup.js. Uses the Tindeq for hang steps:
//
//   - For each hang step: alternate L → R on a single Tindeq.
//   - User pulls into the gripper; force-threshold auto-detect (≥4 kg)
//     triggers the hold timer.
//   - Live force readout shows progress toward the target load.
//   - When the timer reaches the target hold duration, the display
//     turns green to signal release.
//   - User releases; auto-detect ends the rep; advance to next hand
//     or to rest.
//
// Between Crusher and Micro steps, prompt the user to swap the Tindeq
// to the other gripper.
//
// Pullup finisher uses a manual tap counter (no Tindeq).
//
// State machine:
//   preview        — protocol overview, Start button
//   needs-tindeq   — Tindeq not connected, ask user to connect first
//   swap-prompt    — between Crusher and Micro: "Swap Tindeq to Micro"
//   hang-armed     — auto-detect armed, waiting for user to pull
//   hang-active    — hold timer counting up (force ≥ 4 kg)
//   rest           — countdown timer between hands or steps
//   pullup         — tap counter for finisher reps
//   done           — completion

import React, { useEffect, useMemo, useRef, useState } from "react";
import { Card, Btn } from "../ui/components.js";
import { C } from "../ui/theme.js";
import { fmtW } from "../ui/format.js";
import { GRIP_COLORS } from "../ui/grip-colors.js";
import { generateWarmupProtocol } from "../model/warmup.js";
// Same big-timer + force-gauge primitives the finger-training active
// rep uses. Sharing the components keeps the warmup hang visually
// identical to a real rep: same font scale, same color thresholds,
// same Avg/Max sub-row. Lives in cards/LiveForceCard.jsx.
import { BigTimer, ForceGauge } from "./cards/LiveForceCard.jsx";

function fmtSec(s) {
  if (s == null || !isFinite(s)) return "0";
  const sec = Math.max(0, Math.round(s));
  if (sec < 60) return `${sec}`;
  return `${Math.floor(sec / 60)}:${String(sec % 60).padStart(2, "0")}`;
}

export function WarmupView({ history, wLog, bodyWeightKg, tindeq, unit = "lbs", onClose }) {
  const protocol = useMemo(
    () => generateWarmupProtocol({ history, wLog, bodyWeightKg }),
    [history, wLog, bodyWeightKg]
  );

  // ── State machine ──
  const [phase, setPhase] = useState("preview"); // preview|needs-tindeq|swap-prompt|hang-armed|hang-active|rest|pullup|done
  const [stepIdx, setStepIdx] = useState(0);
  const [activeHand, setActiveHand] = useState("L"); // L → R within a hang step
  const [setIdx, setSetIdx] = useState(0);            // for multi-set pullup
  const [pullupReps, setPullupReps] = useState(0);
  const [elapsed, setElapsed] = useState(0);          // sec since hang started
  const [restRemaining, setRestRemaining] = useState(0);

  const tickRef = useRef(null);
  const startTimeRef = useRef(null);

  // Hoisted above the effects below so the auto-detect wiring can
  // reference `currentStep` in its dep array without tripping
  // no-use-before-define. `steps` is read from `protocol.steps` but
  // guarded — the protocol can be ok:false, in which case the early
  // return below renders the can't-generate card and steps stays
  // an empty array. The effects skip work when there's no step.
  const steps = protocol.ok ? protocol.steps : [];
  const currentStep = steps[stepIdx];

  // ── Hang timer (count up while force is held above threshold) ──
  useEffect(() => {
    if (tickRef.current) clearInterval(tickRef.current);
    if (phase === "hang-active") {
      startTimeRef.current = Date.now();
      setElapsed(0);
      tickRef.current = setInterval(() => {
        setElapsed(Math.floor((Date.now() - startTimeRef.current) / 1000));
      }, 200);
    } else if (phase === "rest") {
      const startedAt = Date.now();
      const restSec = currentStep?.restAfterSec || 60;
      setRestRemaining(restSec);
      tickRef.current = setInterval(() => {
        const remaining = restSec - Math.floor((Date.now() - startedAt) / 1000);
        setRestRemaining(Math.max(0, remaining));
        if (remaining <= 0) {
          clearInterval(tickRef.current);
          advanceFromRest();
        }
      }, 200);
    }
    return () => {
      if (tickRef.current) clearInterval(tickRef.current);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [phase, stepIdx, activeHand, setIdx]);

  // ── Tindeq auto-detect wiring ──
  // The previous version re-ran this effect on every change to
  // [phase, stepIdx, activeHand]. That tore down (stopAutoDetect) and
  // immediately re-armed (startAutoDetect) the BLE stream on each
  // hand swap and on every armed↔active flip, which on some clients
  // raced the queued writeValue(CMD_STOP) and writeValue(CMD_START)
  // calls — the Tindeq could end up stopped while the user was still
  // pulling, freezing tindeq.force at the last sampled value (Nathan
  // saw the live weight cap mid-hang). The finger-training side
  // avoids this entirely by registering autoDetect once on mount.
  //
  // Mirror that pattern here: register/unregister only when the user
  // enters or leaves the hang lifecycle (boolean inHangPhase). The L→R
  // hand swap and the armed→active transition stay inside that
  // lifecycle, so the BLE stream stays up continuously and force keeps
  // updating.
  //
  // The auto-detect callbacks need to read fresh React state (the
  // current activeHand, currentStep, etc.). We can't re-register them
  // without restarting the stream, so we keep them in refs and have
  // a stable wrapper dispatch to whatever ref is current. Refs are
  // updated on every render — see the assignments below the effect.
  const onRepStartRef = useRef(null);
  const onRepEndRef   = useRef(null);
  onRepStartRef.current = () => setPhase("hang-active");
  onRepEndRef.current   = () => handleHangComplete();
  const inHangPhase = phase === "hang-armed" || phase === "hang-active";
  useEffect(() => {
    if (!tindeq?.connected || !inHangPhase) return;
    // targetKgRef is a plain ref on the tindeq hook — updating it
    // doesn't restart the stream. Reassign on each effect run so the
    // auto-fail / live-display logic sees the current step's target.
    tindeq.targetKgRef.current = currentStep?.targetLoadKg ?? null;
    tindeq.startAutoDetect(
      () => onRepStartRef.current?.(),
      () => onRepEndRef.current?.(),
    );
    return () => {
      tindeq.stopAutoDetect();
      tindeq.targetKgRef.current = null;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [inHangPhase, stepIdx, tindeq?.connected]);

  // Keep the target ref in sync when activeHand or step changes inside
  // the hang lifecycle (the effect above only runs on lifecycle entry,
  // not on intra-lifecycle transitions). Cheap ref write — no rerender.
  useEffect(() => {
    if (tindeq && inHangPhase) {
      tindeq.targetKgRef.current = currentStep?.targetLoadKg ?? null;
    }
  }, [tindeq, inHangPhase, currentStep, activeHand]);

  if (!protocol.ok) {
    return (
      <Card>
        <div style={{ fontSize: 18, fontWeight: 700, marginBottom: 8 }}>Adaptive Warm-up</div>
        <div style={{ fontSize: 13, color: C.yellow, marginBottom: 12, lineHeight: 1.5 }}>
          ⚠ Can't generate yet
        </div>
        <div style={{ fontSize: 13, color: C.text, lineHeight: 1.6, marginBottom: 16 }}>
          {protocol.reason}
        </div>
        <Btn onClick={onClose} small>Back</Btn>
      </Card>
    );
  }

  // (steps + currentStep hoisted above the effects — see comment up top.)

  // ── Flow control ──
  function startProtocol() {
    if (!tindeq?.connected) {
      setPhase("needs-tindeq");
      return;
    }
    setStepIdx(0);
    setActiveHand("L");
    setSetIdx(0);
    setPullupReps(0);
    enterStep(0, "L");
  }

  function enterStep(idx, hand = "L") {
    const step = steps[idx];
    if (!step) {
      setPhase("done");
      return;
    }
    if (step.type === "hang") {
      // If switching from one grip to another (Crusher → Micro), insert
      // a swap-prompt before arming the next hang.
      const prevStep = steps[idx - 1];
      if (prevStep && prevStep.type === "hang" && prevStep.grip !== step.grip && hand === "L") {
        setPhase("swap-prompt");
      } else {
        setActiveHand(hand);
        setPhase("hang-armed");
      }
    } else if (step.type === "pullup") {
      setPullupReps(0);
      setPhase("pullup");
    }
  }

  // Called when the Tindeq auto-detect signals a rep has ended (user
  // released). Advance L → R within step, or move to rest after R.
  function handleHangComplete() {
    setElapsed(0);
    if (activeHand === "L") {
      // Move to right hand. Brief inter-hand pause uses the rest path
      // with a short 5s breather.
      setActiveHand("R");
      // Skip rest; go straight back to armed for the right hand.
      setPhase("hang-armed");
    } else {
      // Right hand done — rest before next step.
      if (stepIdx < steps.length - 1 && currentStep.restAfterSec > 0) {
        setPhase("rest");
      } else {
        advanceToNextStep();
      }
    }
  }

  function advanceFromRest() {
    if (currentStep?.type === "pullup" && (currentStep.sets || 1) > setIdx + 1) {
      setSetIdx(s => s + 1);
      setPullupReps(0);
      setPhase("pullup");
      return;
    }
    advanceToNextStep();
  }

  function advanceToNextStep() {
    const next = stepIdx + 1;
    setActiveHand("L");
    setSetIdx(0);
    setPullupReps(0);
    if (next >= steps.length) {
      setPhase("done");
      setStepIdx(next);
    } else {
      setStepIdx(next);
      enterStep(next, "L");
    }
  }

  function completePullupSet() {
    const nSets = currentStep.sets || 1;
    if (setIdx + 1 < nSets) {
      setPhase("rest");
    } else {
      advanceToNextStep();
    }
  }

  function skipStep() {
    advanceToNextStep();
  }

  function confirmSwap() {
    // After swap-prompt, move on into the hang for the new grip, left hand.
    setActiveHand("L");
    setPhase("hang-armed");
  }

  // ── RENDER: PREVIEW ──
  if (phase === "preview") {
    const tindeqConnected = !!tindeq?.connected;
    const tindeqReconnecting = !!tindeq?.reconnecting;
    return (
      <Card>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline", marginBottom: 6 }}>
          <div style={{ fontSize: 18, fontWeight: 800 }}>Adaptive Warm-up</div>
          <div style={{ fontSize: 11, color: C.muted }}>BW {protocol.bodyWeightLbs} lbs</div>
        </div>
        <div style={{ fontSize: 12, color: C.muted, marginBottom: 16, lineHeight: 1.5 }}>
          Tindeq-driven. Loads come from your force curves; targets are short, sub-failure holds. Same intensity for every user, every session. Connect the Crusher first; you'll be prompted to swap to the Micro mid-warmup.
        </div>
        <div style={{ marginBottom: 16 }}>
          {steps.map((s, i) => (
            <div key={s.id} style={{
              display: "flex", justifyContent: "space-between", alignItems: "center",
              padding: "10px 0",
              borderBottom: i < steps.length - 1 ? `1px solid ${C.border}` : "none",
            }}>
              <div style={{ flex: 1 }}>
                <div style={{ fontSize: 11, color: C.muted, marginBottom: 2 }}>Step {i + 1}</div>
                <div style={{ fontSize: 14, fontWeight: 600, color: C.text }}>{s.title}</div>
                <div style={{ fontSize: 11, color: C.muted, marginTop: 2 }}>
                  {s.intensityLabel}
                  {i < steps.length - 1 && ` · rest ${fmtSec(s.restAfterSec)}s`}
                </div>
              </div>
              <div style={{ textAlign: "right", marginLeft: 12 }}>
                {s.type === "hang" ? (
                  <>
                    <div style={{ fontSize: 22, fontWeight: 800, color: C.purple, lineHeight: 1, fontVariantNumeric: "tabular-nums" }}>
                      {fmtW(s.targetLoadKg, unit)}
                    </div>
                    <div style={{ fontSize: 10, color: C.muted, marginTop: 2 }}>
                      {unit} · {s.targetSec}s
                    </div>
                  </>
                ) : (
                  <>
                    <div style={{ fontSize: 22, fontWeight: 800, color: C.purple, lineHeight: 1 }}>
                      {s.targetReps}×{s.sets || 1}
                    </div>
                    <div style={{ fontSize: 10, color: C.muted, marginTop: 2 }}>reps × sets</div>
                  </>
                )}
              </div>
            </div>
          ))}
        </div>
        <div style={{ fontSize: 11, color: C.muted, marginBottom: 12, lineHeight: 1.5, fontStyle: "italic" }}>
          Pullup count: {protocol.pullupSource.sourceText}
          {protocol.pullupSource.count != null && ` (${protocol.pullupSource.count})`}.
          Nothing here gets logged as training data.
        </div>

        {/* Tindeq connect row — placed directly above the Start button
            so the connection prerequisite reads as a step you take
            right before tapping Start. Mirrors the connect card on
            Session Setup but condensed for inline use. */}
        <div style={{
          background: C.bg, border: `1px solid ${C.border}`,
          borderRadius: 10, padding: "10px 12px", marginBottom: 12,
        }}>
          <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
            <div style={{ flex: 1, minWidth: 0 }}>
              <div style={{ fontSize: 13, fontWeight: 600 }}>Tindeq Progressor</div>
              <div style={{ fontSize: 11, color: tindeqConnected ? C.green : C.muted }}>
                {tindeqConnected
                  ? "Connected ✓"
                  : tindeqReconnecting
                    ? "Reconnecting…"
                    : tindeq?.bleError || "Not connected"}
              </div>
            </div>
            <div style={{ display: "flex", gap: 8 }}>
              {tindeqConnected && (
                <Btn small onClick={tindeq.tare} color={C.muted}>Tare</Btn>
              )}
              <Btn
                small
                onClick={() => tindeq?.connect?.()}
                disabled={tindeqConnected || tindeqReconnecting}
                color={tindeqConnected ? C.green : tindeqReconnecting ? C.orange : C.blue}
              >
                {tindeqConnected ? "Connected" : tindeqReconnecting ? "Reconnecting…" : "Connect Tindeq"}
              </Btn>
            </div>
          </div>
          {tindeqConnected && (
            <div style={{ marginTop: 6, fontSize: 11, color: C.muted }}>
              Live force: <b style={{ color: C.blue }}>{fmtW(tindeq.force, unit)} {unit}</b> · tap Tare to zero before starting.
            </div>
          )}
        </div>

        <div style={{ display: "flex", gap: 10 }}>
          <Btn
            onClick={startProtocol}
            color={C.green}
            disabled={!tindeqConnected}
          >
            Start
          </Btn>
          <Btn onClick={onClose} color={C.border} small>Back</Btn>
        </div>
      </Card>
    );
  }

  // ── RENDER: NEEDS-TINDEQ (fallback for mid-warmup disconnect) ──
  if (phase === "needs-tindeq") {
    return (
      <Card>
        <div style={{ fontSize: 18, fontWeight: 700, marginBottom: 8 }}>Connect the Tindeq</div>
        <div style={{ fontSize: 13, color: C.text, lineHeight: 1.6, marginBottom: 16 }}>
          The warm-up uses real-time force feedback to hit prescribed loads. Connect your Tindeq (with the Crusher gripper attached), then come back and tap Start.
        </div>
        <Btn onClick={() => setPhase("preview")} small>Back to preview</Btn>
      </Card>
    );
  }

  // ── RENDER: SWAP-PROMPT (between Crusher and Micro steps) ──
  if (phase === "swap-prompt") {
    return (
      <Card>
        <div style={{ fontSize: 11, color: C.muted, letterSpacing: 0.5, textTransform: "uppercase", marginBottom: 8 }}>
          Step {stepIdx + 1} of {steps.length}
        </div>
        <div style={{ fontSize: 22, fontWeight: 800, marginBottom: 10 }}>
          Swap to <span style={{ color: GRIP_COLORS[currentStep.grip] }}>{currentStep.grip}</span>
        </div>
        <div style={{ fontSize: 13, color: C.text, lineHeight: 1.6, marginBottom: 16 }}>
          Detach the Tindeq from the Crusher and attach it to the Micro gripper. Tap Continue when ready.
        </div>
        <div style={{ display: "flex", gap: 10 }}>
          <Btn onClick={confirmSwap} color={C.green}>Continue</Btn>
          <Btn onClick={onClose} color={C.border} small>End</Btn>
        </div>
      </Card>
    );
  }

  // ── RENDER: HANG (armed or active) ──
  // Layout mirrors the finger-training active-rep card so the warmup
  // hang feels identical to a real rep: BigTimer up top, ForceGauge
  // below. Pre-pull (hang-armed) shows a target-load callout instead
  // of the timer/gauge so the user knows what they're aiming for
  // before the auto-detect catches the pull-start.
  if (phase === "hang-armed" || phase === "hang-active") {
    const target = currentStep.targetSec;
    const handLabel = activeHand === "L" ? "Left Hand" : "Right Hand";
    return (
      <Card>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline", marginBottom: 12 }}>
          <div style={{ fontSize: 11, color: C.muted, letterSpacing: 0.5, textTransform: "uppercase" }}>
            Step {stepIdx + 1} of {steps.length} · {currentStep.intensityLabel}
          </div>
          <div style={{ fontSize: 11, color: C.muted, fontWeight: 600 }}>
            <span style={{ color: GRIP_COLORS[currentStep.grip] }}>{currentStep.grip}</span> · {handLabel}
          </div>
        </div>
        <div style={{ fontSize: 22, fontWeight: 800, marginBottom: 10 }}>{currentStep.title}</div>

        {phase === "hang-armed" ? (
          // Pre-pull callout — target load and duration. Once the
          // user pulls (force ≥ 4 kg) the auto-detect flips to
          // hang-active and the BigTimer/ForceGauge replace this.
          <div style={{
            background: C.bg, border: `1px solid ${C.border}`,
            borderRadius: 12, padding: "20px 16px", marginBottom: 12,
            textAlign: "center",
          }}>
            <div style={{ fontSize: 11, color: C.muted, letterSpacing: 0.5, textTransform: "uppercase", marginBottom: 6 }}>
              Pull to begin
            </div>
            <div style={{ fontSize: 44, fontWeight: 900, color: C.purple, lineHeight: 1, fontVariantNumeric: "tabular-nums" }}>
              {fmtW(currentStep.targetLoadKg, unit)} {unit}
            </div>
            <div style={{ fontSize: 12, color: C.muted, marginTop: 6 }}>
              hold for {target}s
            </div>
            {/* Live force readout while armed but not yet pulling, so
                the user can confirm the Tindeq is reading and tare if
                needed. Number stays gray until the pull-detect fires. */}
            {tindeq?.connected && (
              <div style={{ marginTop: 14, fontSize: 12, color: C.muted }}>
                Live: <b style={{
                  color: C.text, fontVariantNumeric: "tabular-nums",
                }}>{fmtW(tindeq.force, unit)} {unit}</b>
              </div>
            )}
          </div>
        ) : (
          // Active hold — same primitives as finger training.
          <>
            <BigTimer
              seconds={elapsed}
              targetSeconds={target}
              running={true}
            />
            {tindeq?.connected ? (
              <ForceGauge
                force={tindeq.force}
                avg={tindeq.avgForce}
                peak={tindeq.peak}
                targetKg={currentStep.targetLoadKg}
                unit={unit}
              />
            ) : (
              <div style={{ fontSize: 12, color: C.muted, textAlign: "center", marginTop: 8 }}>
                Tindeq disconnected — release when target hold time is reached.
              </div>
            )}
          </>
        )}

        <div style={{ display: "flex", gap: 10, marginTop: 12 }}>
          <Btn onClick={skipStep} color={C.border} small>Skip step</Btn>
          <div style={{ flex: 1 }} />
          <Btn onClick={onClose} color={C.border} small>End</Btn>
        </div>
      </Card>
    );
  }

  // ── RENDER: REST ──
  if (phase === "rest") {
    const nextStep = steps[stepIdx + 1];
    const isMidPullupSet = currentStep?.type === "pullup" && (currentStep.sets || 1) > setIdx + 1;
    return (
      <Card>
        <div style={{ fontSize: 11, color: C.muted, letterSpacing: 0.5, textTransform: "uppercase", marginBottom: 8 }}>
          Rest
        </div>
        <div style={{
          background: C.bg, border: `1px solid ${C.border}`,
          borderRadius: 12, padding: "20px 16px", marginBottom: 16,
          textAlign: "center",
        }}>
          <div style={{ fontSize: 56, fontWeight: 900, color: C.blue, lineHeight: 1, fontVariantNumeric: "tabular-nums" }}>
            {fmtSec(restRemaining)}
          </div>
          <div style={{ fontSize: 12, color: C.muted, marginTop: 6 }}>seconds remaining</div>
        </div>
        <div style={{ fontSize: 12, color: C.muted, marginBottom: 16, lineHeight: 1.5 }}>
          {isMidPullupSet ? (
            <>Next: <b style={{ color: C.text }}>set {setIdx + 2} of {currentStep.sets}</b>.</>
          ) : nextStep ? (
            <>Up next: <b style={{ color: C.text }}>{nextStep.title}</b> · {nextStep.intensityLabel}.</>
          ) : (
            <>Final step coming up.</>
          )}
        </div>
        <div style={{ display: "flex", gap: 10 }}>
          <Btn onClick={advanceFromRest} color={C.blue}>Skip rest</Btn>
          <div style={{ flex: 1 }} />
          <Btn onClick={onClose} color={C.border} small>End</Btn>
        </div>
      </Card>
    );
  }

  // ── RENDER: PULLUP ──
  if (phase === "pullup") {
    const setsTotal = currentStep.sets || 1;
    return (
      <Card>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline", marginBottom: 12 }}>
          <div style={{ fontSize: 11, color: C.muted, letterSpacing: 0.5, textTransform: "uppercase" }}>
            Step {stepIdx + 1} of {steps.length} · Set {setIdx + 1} of {setsTotal}
          </div>
          <div style={{ fontSize: 11, color: C.muted }}>BW {protocol.bodyWeightLbs} lbs</div>
        </div>
        <div style={{ fontSize: 22, fontWeight: 800, marginBottom: 10 }}>{currentStep.title}</div>
        <div style={{ fontSize: 12, color: C.muted, marginBottom: 16, lineHeight: 1.5 }}>
          {currentStep.description}
        </div>
        <div style={{
          background: C.bg, border: `1px solid ${C.border}`,
          borderRadius: 12, padding: "20px 16px", marginBottom: 16,
          textAlign: "center",
        }}>
          <div style={{ fontSize: 11, color: C.muted, letterSpacing: 0.5, textTransform: "uppercase", marginBottom: 6 }}>Reps</div>
          <div style={{
            fontSize: 64, fontWeight: 900,
            color: pullupReps >= currentStep.targetReps ? C.green : C.purple,
            lineHeight: 1, fontVariantNumeric: "tabular-nums",
          }}>
            {pullupReps}
          </div>
          <div style={{ fontSize: 12, color: C.muted, marginTop: 6 }}>
            target {currentStep.targetReps}
          </div>
          <div style={{ display: "flex", gap: 10, marginTop: 14, justifyContent: "center" }}>
            <Btn onClick={() => setPullupReps(r => Math.max(0, r - 1))} color={C.border} small>−</Btn>
            <Btn onClick={() => setPullupReps(r => r + 1)} color={C.green}>+1 rep</Btn>
          </div>
        </div>
        <div style={{ display: "flex", gap: 10 }}>
          <Btn onClick={completePullupSet} color={C.blue}>
            {setIdx + 1 < setsTotal ? "Set done" : "Done"}
          </Btn>
          <Btn onClick={skipStep} color={C.border} small>Skip</Btn>
          <div style={{ flex: 1 }} />
          <Btn onClick={onClose} color={C.border} small>End</Btn>
        </div>
      </Card>
    );
  }

  // ── RENDER: DONE ──
  if (phase === "done") {
    return (
      <Card>
        <div style={{ fontSize: 22, fontWeight: 800, marginBottom: 8, color: C.green }}>
          ✓ Warm-up complete
        </div>
        <div style={{ fontSize: 13, color: C.text, lineHeight: 1.6, marginBottom: 16 }}>
          Forearms primed, fingers awake, neither flash-pumped nor under-cooked. The video calls for ~10 minutes of full rest now to clear fatigue, then you're ready for early goes.
        </div>
        <div style={{ fontSize: 12, color: C.muted, marginBottom: 16, lineHeight: 1.5, fontStyle: "italic" }}>
          Nothing here was logged — warm-up reps don't update the force curve.
        </div>
        <Btn onClick={onClose} color={C.green}>Close</Btn>
      </Card>
    );
  }

  return null;
}

export default WarmupView;
