// ─────────────────────────────────────────────────────────────
// ADAPTIVE WARM-UP VIEW (Tindeq-driven)
// ─────────────────────────────────────────────────────────────
// Walks the user through the warm-up protocol generated by
// src/model/warmup.js. Two protocol modes:
//
//   - boulder: perfusion holds (F(60s)-anchored, sub-failure) +
//              Micro BORK potentiation primer (5 × ~5s MVC, 45s rest)
//   - route:   perfusion only, longer Micro hold for endurance prep
//
// The preview screen offers a pill toggle between modes; selection
// persists in localStorage via LS_WARMUP_MODE_KEY.
//
// Hang step lifecycle:
//   - User pulls; force-threshold auto-detect (≥4 kg) triggers the
//     hold timer.
//   - BigTimer counts up; ForceGauge shows live force vs target.
//   - At targetSec, the rep auto-advances (endRepAndRequireRelease
//     blocks the next pull-detect until force drops, so the user's
//     continued grip doesn't immediately retrigger).
//   - Early release also ends the rep via auto-detect onRepEnd.
//
// BORK step lifecycle (boulder mode only):
//   - 5 reps × ~5s max-effort pulls, 45s rest between.
//   - No target load — the user just pulls as hard as possible.
//   - Auto-advance at holdSec (5s) per rep, same as hang.
//   - Between-rep rest uses restBetweenSec; after-step rest uses
//     restAfterSec (or skipped if pullup finisher comes next).
//
// Between Crusher and Micro steps, prompt the user to swap the
// Tindeq to the other gripper.
//
// Pullup finisher uses a manual tap counter (no Tindeq).
//
// State machine:
//   preview        — protocol overview, mode toggle, Start button
//   needs-tindeq   — Tindeq not connected, ask user to connect first
//   swap-prompt    — between Crusher and Micro: "Swap Tindeq to Micro"
//   hang-armed     — auto-detect armed, waiting for user to pull
//   hang-active    — hold timer counting up (force ≥ 4 kg). For BORK
//                    steps, this is the per-rep active phase.
//   rest           — countdown timer between steps or between BORK reps
//   pullup         — tap counter for finisher reps
//   done           — completion

import React, { useEffect, useMemo, useRef, useState } from "react";
import { Card, Btn } from "../ui/components.js";
import { C } from "../ui/theme.js";
import { fmtW } from "../ui/format.js";
import { GRIP_COLORS } from "../ui/grip-colors.js";
import { generateWarmupProtocol } from "../model/warmup.js";
import { loadLS, saveLS, LS_WARMUP_MODE_KEY } from "../lib/storage.js";
// Same big-timer + force-gauge primitives the finger-training active
// rep uses. Sharing the components keeps the warmup hang visually
// identical to a real rep: same font scale, same color thresholds,
// same Avg/Max sub-row. Lives in cards/LiveForceCard.jsx.
import { BigTimer, ForceGauge } from "./cards/LiveForceCard.jsx";

function fmtSec(s) {
  if (s == null || !isFinite(s)) return "0";
  const sec = Math.max(0, Math.round(s));
  if (sec < 60) return `${sec}`;
  return `${Math.floor(sec / 60)}:${String(sec % 60).padStart(2, "0")}`;
}

export function WarmupView({ history, wLog, bodyWeightKg, tindeq, unit = "lbs", onClose }) {
  // ── Warmup mode (boulder / route) ──
  // Persisted to LS so the user's last choice carries across sessions.
  // Default to "boulder" — most users are bouldering most of the time,
  // and the BORK potentiation is the more involved option, so route
  // is the explicit opt-in.
  const [mode, setMode] = useState(() => {
    const saved = loadLS(LS_WARMUP_MODE_KEY);
    return saved === "route" ? "route" : "boulder";
  });
  const updateMode = (next) => {
    setMode(next);
    saveLS(LS_WARMUP_MODE_KEY, next);
  };

  const protocol = useMemo(
    () => generateWarmupProtocol({ history, wLog, bodyWeightKg, mode }),
    [history, wLog, bodyWeightKg, mode]
  );

  // ── State machine ──
  const [phase, setPhase] = useState("preview"); // preview|needs-tindeq|swap-prompt|hang-armed|hang-active|rest|pullup|done
  const [stepIdx, setStepIdx] = useState(0);
  // Each warmup hang is a single two-handed pull (titles literally
  // say "Two-Handed Crusher" / "Two-Handed Micro"). An earlier version
  // tracked activeHand and alternated L → R within a step; that's
  // been removed since the protocol's intent is one bilateral hold
  // per step.
  const [setIdx, setSetIdx] = useState(0);            // for multi-set pullup
  const [pullupReps, setPullupReps] = useState(0);
  const [elapsed, setElapsed] = useState(0);          // sec since hang started
  const [restRemaining, setRestRemaining] = useState(0);
  // For BORK steps: which rep we're currently on (0..reps-1). Between
  // bork reps the rest phase reads currentStep.restBetweenSec instead
  // of restAfterSec; after the final rep the regular restAfterSec
  // applies. Reset to 0 on any new step.
  const [borkRepIdx, setBorkRepIdx] = useState(0);

  const tickRef = useRef(null);
  const startTimeRef = useRef(null);

  // Hoisted above the effects below so the auto-detect wiring can
  // reference `currentStep` in its dep array without tripping
  // no-use-before-define. `steps` is read from `protocol.steps` but
  // guarded — the protocol can be ok:false, in which case the early
  // return below renders the can't-generate card and steps stays
  // an empty array. The effects skip work when there's no step.
  const steps = protocol.ok ? protocol.steps : [];
  const currentStep = steps[stepIdx];

  // ── Hang timer (count up while force is held above threshold) ──
  // The hang phase auto-advances when elapsed reaches the prescribed
  // targetSec — same intent as the rest countdown auto-advancing at
  // 0. Without this, the warmup just *suggests* a 30s hold and waits
  // for the user to release; with it, the protocol enforces the
  // prescribed schedule. If the user releases before target, the
  // auto-detect rep-end still fires (handleHangComplete from the BLE
  // callback), so an early release is graceful, not blocked.
  //
  // When auto-end fires while the user is still pulling, we also tell
  // the Tindeq to require a real release before re-arming pull-detect
  // (see tindeq.endRepAndRequireRelease). Otherwise their continued
  // grip on the L hand would immediately trigger an onRepStart for the
  // R hand the moment we transition to hang-armed.
  useEffect(() => {
    if (tickRef.current) clearInterval(tickRef.current);
    if (phase === "hang-active") {
      // BORK steps use `holdSec` (per-rep); hangs use `targetSec`.
      // Both paths auto-advance at the prescribed duration via
      // handleHangComplete; the rest of the BORK rep machinery is
      // in that handler.
      const targetSec = currentStep?.type === "bork"
        ? (currentStep?.holdSec || 0)
        : (currentStep?.targetSec || 0);
      startTimeRef.current = Date.now();
      setElapsed(0);
      tickRef.current = setInterval(() => {
        const ms = Date.now() - startTimeRef.current;
        const secs = Math.floor(ms / 1000);
        setElapsed(secs);
        // Auto-advance once we've held to target. Check on the
        // millisecond clock (not `secs`) so a tick that lands a
        // hair past target still fires — setInterval drift can
        // skip a 1s boundary otherwise.
        if (targetSec > 0 && ms >= targetSec * 1000) {
          clearInterval(tickRef.current);
          tickRef.current = null;
          if (tindeq?.endRepAndRequireRelease) {
            tindeq.endRepAndRequireRelease();
          }
          handleHangComplete();
        }
      }, 200);
    } else if (phase === "rest") {
      const startedAt = Date.now();
      // BORK between-rep rest uses restBetweenSec; every other rest
      // (between-step, between-pullup-set, after-BORK-final-rep)
      // uses restAfterSec.
      const isBorkBetweenReps = currentStep?.type === "bork"
        && borkRepIdx + 1 < (currentStep?.reps || 0);
      const restSec = isBorkBetweenReps
        ? (currentStep?.restBetweenSec || 45)
        : (currentStep?.restAfterSec || 60);
      setRestRemaining(restSec);
      tickRef.current = setInterval(() => {
        const remaining = restSec - Math.floor((Date.now() - startedAt) / 1000);
        setRestRemaining(Math.max(0, remaining));
        if (remaining <= 0) {
          clearInterval(tickRef.current);
          advanceFromRest();
        }
      }, 200);
    }
    return () => {
      if (tickRef.current) clearInterval(tickRef.current);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [phase, stepIdx, setIdx, borkRepIdx]);

  // ── Tindeq auto-detect wiring ──
  // The earlier version re-ran this effect on every phase change.
  // That tore down (stopAutoDetect) and immediately re-armed
  // (startAutoDetect) the BLE stream on every armed↔active flip,
  // which on some clients raced the queued writeValue(CMD_STOP)
  // and writeValue(CMD_START) calls — the Tindeq could end up
  // stopped while the user was still pulling, freezing tindeq.force
  // at the last sampled value. The finger-training side avoids this
  // by registering autoDetect once on mount.
  //
  // Mirror that pattern here: register/unregister only when the user
  // enters or leaves the hang lifecycle (boolean inHangPhase). The
  // armed→active transition stays inside that lifecycle, so the BLE
  // stream stays up continuously and force keeps updating.
  //
  // The auto-detect callbacks need to read fresh React state. We can't
  // re-register them without restarting the stream, so we keep them
  // in refs and have a stable wrapper dispatch to whatever ref is
  // current. Refs are updated on every render — see the assignments
  // below the effect.
  const onRepStartRef = useRef(null);
  const onRepEndRef   = useRef(null);
  onRepStartRef.current = () => setPhase("hang-active");
  onRepEndRef.current   = () => handleHangComplete();
  const inHangPhase = phase === "hang-armed" || phase === "hang-active";
  useEffect(() => {
    if (!tindeq?.connected || !inHangPhase) return;
    // targetKgRef is a plain ref on the tindeq hook — updating it
    // doesn't restart the stream. Reassign on each effect run so the
    // auto-fail / live-display logic sees the current step's target.
    tindeq.targetKgRef.current = currentStep?.targetLoadKg ?? null;
    tindeq.startAutoDetect(
      () => onRepStartRef.current?.(),
      () => onRepEndRef.current?.(),
    );
    return () => {
      tindeq.stopAutoDetect();
      tindeq.targetKgRef.current = null;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [inHangPhase, stepIdx, tindeq?.connected]);

  // Keep the target ref in sync when the step changes inside the
  // hang lifecycle (the effect above only runs on lifecycle entry,
  // not on intra-lifecycle transitions). Cheap ref write — no rerender.
  useEffect(() => {
    if (tindeq && inHangPhase) {
      tindeq.targetKgRef.current = currentStep?.targetLoadKg ?? null;
    }
  }, [tindeq, inHangPhase, currentStep]);

  if (!protocol.ok) {
    return (
      <Card>
        <div style={{ fontSize: 18, fontWeight: 700, marginBottom: 8 }}>Adaptive Warm-up</div>
        <div style={{ fontSize: 13, color: C.yellow, marginBottom: 12, lineHeight: 1.5 }}>
          ⚠ Can't generate yet
        </div>
        <div style={{ fontSize: 13, color: C.text, lineHeight: 1.6, marginBottom: 16 }}>
          {protocol.reason}
        </div>
        <Btn onClick={onClose} small>Back</Btn>
      </Card>
    );
  }

  // (steps + currentStep hoisted above the effects — see comment up top.)

  // ── Flow control ──
  // Each warmup hang is a single two-handed hold (the steps are titled
  // "Two-Handed Crusher" / "Two-Handed Micro"). Earlier versions did
  // separate L then R reps per step; that's been removed — one pull,
  // one hold, advance to rest.
  function startProtocol() {
    if (!tindeq?.connected) {
      setPhase("needs-tindeq");
      return;
    }
    setStepIdx(0);
    setSetIdx(0);
    setPullupReps(0);
    enterStep(0);
  }

  function enterStep(idx) {
    const step = steps[idx];
    if (!step) {
      setPhase("done");
      return;
    }
    // Hang and BORK both arm the same way — autoDetect waits for a
    // pull-start, then the hang-active timer takes over. The only
    // difference is how handleHangComplete loops on completion
    // (BORK has 5 reps, hang has 1).
    if (step.type === "hang" || step.type === "bork") {
      setBorkRepIdx(0);
      // If switching from one grip to another (e.g. Crusher → Micro),
      // insert a swap-prompt before arming so the user has time to
      // change which gripper the Tindeq is mounted on.
      const prevStep = steps[idx - 1];
      const prevGrip = prevStep && (prevStep.type === "hang" || prevStep.type === "bork") ? prevStep.grip : null;
      if (prevGrip && prevGrip !== step.grip) {
        setPhase("swap-prompt");
      } else {
        setPhase("hang-armed");
      }
    } else if (step.type === "pullup") {
      setPullupReps(0);
      setPhase("pullup");
    }
  }

  // Called when the active hang (or BORK rep) ends — either auto-
  // advanced at targetSec/holdSec or released early.
  //
  //   - hang step: always go straight to rest (or next step if last)
  //   - bork step: if more reps remain, go to between-rep rest;
  //                if last rep, go to after-step rest (or next step
  //                if this was the last step)
  function handleHangComplete() {
    setElapsed(0);
    const isBork = currentStep?.type === "bork";
    const isLastStep = stepIdx >= steps.length - 1;
    if (isBork && borkRepIdx + 1 < (currentStep?.reps || 0)) {
      // More BORK reps to do — between-rep rest. The rest-timer
      // effect reads borkRepIdx to pick restBetweenSec vs restAfterSec.
      setPhase("rest");
      return;
    }
    if (!isLastStep && currentStep?.restAfterSec > 0) {
      setPhase("rest");
    } else {
      advanceToNextStep();
    }
  }

  function advanceFromRest() {
    // BORK: if we just finished a between-rep rest, arm the next rep.
    if (currentStep?.type === "bork" && borkRepIdx + 1 < (currentStep?.reps || 0)) {
      setBorkRepIdx(i => i + 1);
      setPhase("hang-armed");
      return;
    }
    // Multi-set pullup loop (unchanged).
    if (currentStep?.type === "pullup" && (currentStep.sets || 1) > setIdx + 1) {
      setSetIdx(s => s + 1);
      setPullupReps(0);
      setPhase("pullup");
      return;
    }
    advanceToNextStep();
  }

  function advanceToNextStep() {
    const next = stepIdx + 1;
    setSetIdx(0);
    setPullupReps(0);
    setBorkRepIdx(0);
    if (next >= steps.length) {
      setPhase("done");
      setStepIdx(next);
    } else {
      setStepIdx(next);
      enterStep(next);
    }
  }

  function completePullupSet() {
    const nSets = currentStep.sets || 1;
    if (setIdx + 1 < nSets) {
      setPhase("rest");
    } else {
      advanceToNextStep();
    }
  }

  function skipStep() {
    advanceToNextStep();
  }

  function confirmSwap() {
    // After swap-prompt, move on into the hang for the new grip.
    setPhase("hang-armed");
  }

  // ── RENDER: PREVIEW ──
  if (phase === "preview") {
    const tindeqConnected = !!tindeq?.connected;
    const tindeqReconnecting = !!tindeq?.reconnecting;
    // Mode toggle helper — mirrors the discipline pill pattern from
    // ClimbingAnalysisView so the warmup card feels visually
    // consistent with the rest of the app.
    const modePill = (key, label, desc) => {
      const active = mode === key;
      return (
        <button
          key={key}
          onClick={() => updateMode(key)}
          style={{
            flex: 1, padding: "8px 10px", borderRadius: 10,
            background: active ? C.purple : C.bg,
            color: active ? "#fff" : C.muted,
            border: `1px solid ${active ? C.purple : C.border}`,
            fontWeight: active ? 700 : 500, fontSize: 13, cursor: "pointer",
            textAlign: "center", lineHeight: 1.2,
          }}
          title={desc}
        >
          {label}
        </button>
      );
    };
    return (
      <Card>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline", marginBottom: 6 }}>
          <div style={{ fontSize: 18, fontWeight: 800 }}>Adaptive Warm-up</div>
          <div style={{ fontSize: 11, color: C.muted }}>BW {protocol.bodyWeightLbs} lbs</div>
        </div>
        <div style={{ fontSize: 12, color: C.muted, marginBottom: 12, lineHeight: 1.5 }}>
          Tindeq-driven. Perfusion holds anchored to F(60s)
          {mode === "boulder"
            ? ", plus a Micro MVC primer at the end (PAP for hard pulls)."
            : ", longer Micro hold for endurance prep — no BORK."}
          {" Connect the Crusher first; you'll be prompted to swap to the Micro mid-warmup."}
        </div>
        {/* Mode toggle: boulder (with BORK) or route (perfusion only).
            Persists to LS_WARMUP_MODE_KEY. */}
        <div style={{ display: "flex", gap: 8, marginBottom: 16 }}>
          {modePill("boulder", "🪨 Bouldering", "Perfusion + Micro BORK MVC potentiation primer (PAP for hard moves).")}
          {modePill("route", "🧗 Routes", "Perfusion only, longer Micro hold for endurance prep.")}
        </div>
        <div style={{ marginBottom: 16 }}>
          {steps.map((s, i) => (
            <div key={s.id} style={{
              display: "flex", justifyContent: "space-between", alignItems: "center",
              padding: "10px 0",
              borderBottom: i < steps.length - 1 ? `1px solid ${C.border}` : "none",
            }}>
              <div style={{ flex: 1 }}>
                <div style={{ fontSize: 11, color: C.muted, marginBottom: 2 }}>Step {i + 1}</div>
                <div style={{ fontSize: 14, fontWeight: 600, color: C.text }}>{s.title}</div>
                <div style={{ fontSize: 11, color: C.muted, marginTop: 2 }}>
                  {s.intensityLabel}
                  {i < steps.length - 1 && ` · rest ${fmtSec(s.restAfterSec)}s`}
                </div>
              </div>
              <div style={{ textAlign: "right", marginLeft: 12 }}>
                {s.type === "hang" ? (
                  <>
                    <div style={{ fontSize: 22, fontWeight: 800, color: C.purple, lineHeight: 1, fontVariantNumeric: "tabular-nums" }}>
                      {fmtW(s.targetLoadKg, unit)}
                    </div>
                    <div style={{ fontSize: 10, color: C.muted, marginTop: 2 }}>
                      {unit} · {s.targetSec}s
                    </div>
                  </>
                ) : s.type === "bork" ? (
                  <>
                    <div style={{ fontSize: 22, fontWeight: 800, color: C.purple, lineHeight: 1 }}>
                      MVC
                    </div>
                    <div style={{ fontSize: 10, color: C.muted, marginTop: 2 }}>
                      {s.reps}×{s.holdSec}s · {fmtSec(s.restBetweenSec)}s rest
                    </div>
                  </>
                ) : (
                  <>
                    <div style={{ fontSize: 22, fontWeight: 800, color: C.purple, lineHeight: 1 }}>
                      {s.targetReps}×{s.sets || 1}
                    </div>
                    <div style={{ fontSize: 10, color: C.muted, marginTop: 2 }}>reps × sets</div>
                  </>
                )}
              </div>
            </div>
          ))}
        </div>
        <div style={{ fontSize: 11, color: C.muted, marginBottom: 12, lineHeight: 1.5, fontStyle: "italic" }}>
          Pullup count: {protocol.pullupSource.sourceText}
          {protocol.pullupSource.count != null && ` (${protocol.pullupSource.count})`}.
          Nothing here gets logged as training data.
        </div>

        {/* Tindeq connect row — placed directly above the Start button
            so the connection prerequisite reads as a step you take
            right before tapping Start. Mirrors the connect card on
            Session Setup but condensed for inline use. */}
        <div style={{
          background: C.bg, border: `1px solid ${C.border}`,
          borderRadius: 10, padding: "10px 12px", marginBottom: 12,
        }}>
          <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
            <div style={{ flex: 1, minWidth: 0 }}>
              <div style={{ fontSize: 13, fontWeight: 600 }}>Tindeq Progressor</div>
              <div style={{ fontSize: 11, color: tindeqConnected ? C.green : C.muted }}>
                {tindeqConnected
                  ? "Connected ✓"
                  : tindeqReconnecting
                    ? "Reconnecting…"
                    : tindeq?.bleError || "Not connected"}
              </div>
            </div>
            <div style={{ display: "flex", gap: 8 }}>
              {tindeqConnected && (
                <Btn small onClick={tindeq.tare} color={C.muted}>Tare</Btn>
              )}
              <Btn
                small
                onClick={() => tindeq?.connect?.()}
                disabled={tindeqConnected || tindeqReconnecting}
                color={tindeqConnected ? C.green : tindeqReconnecting ? C.orange : C.blue}
              >
                {tindeqConnected ? "Connected" : tindeqReconnecting ? "Reconnecting…" : "Connect Tindeq"}
              </Btn>
            </div>
          </div>
          {tindeqConnected && (
            <div style={{ marginTop: 6, fontSize: 11, color: C.muted }}>
              Live force: <b style={{ color: C.blue }}>{fmtW(tindeq.force, unit)} {unit}</b> · tap Tare to zero before starting.
            </div>
          )}
        </div>

        <div style={{ display: "flex", gap: 10 }}>
          <Btn
            onClick={startProtocol}
            color={C.green}
            disabled={!tindeqConnected}
          >
            Start
          </Btn>
          <Btn onClick={onClose} color={C.border} small>Back</Btn>
        </div>
      </Card>
    );
  }

  // ── RENDER: NEEDS-TINDEQ (fallback for mid-warmup disconnect) ──
  if (phase === "needs-tindeq") {
    return (
      <Card>
        <div style={{ fontSize: 18, fontWeight: 700, marginBottom: 8 }}>Connect the Tindeq</div>
        <div style={{ fontSize: 13, color: C.text, lineHeight: 1.6, marginBottom: 16 }}>
          The warm-up uses real-time force feedback to hit prescribed loads. Connect your Tindeq (with the Crusher gripper attached), then come back and tap Start.
        </div>
        <Btn onClick={() => setPhase("preview")} small>Back to preview</Btn>
      </Card>
    );
  }

  // ── RENDER: SWAP-PROMPT (between Crusher and Micro steps) ──
  if (phase === "swap-prompt") {
    return (
      <Card>
        <div style={{ fontSize: 11, color: C.muted, letterSpacing: 0.5, textTransform: "uppercase", marginBottom: 8 }}>
          Step {stepIdx + 1} of {steps.length}
        </div>
        <div style={{ fontSize: 22, fontWeight: 800, marginBottom: 10 }}>
          Swap to <span style={{ color: GRIP_COLORS[currentStep.grip] }}>{currentStep.grip}</span>
        </div>
        <div style={{ fontSize: 13, color: C.text, lineHeight: 1.6, marginBottom: 16 }}>
          Detach the Tindeq from the Crusher and attach it to the Micro gripper. Tap Continue when ready.
        </div>
        <div style={{ display: "flex", gap: 10 }}>
          <Btn onClick={confirmSwap} color={C.green}>Continue</Btn>
          <Btn onClick={onClose} color={C.border} small>End</Btn>
        </div>
      </Card>
    );
  }

  // ── RENDER: HANG / BORK (armed or active) ──
  // Layout mirrors the finger-training active-rep card so the warmup
  // hang feels identical to a real rep: BigTimer up top, ForceGauge
  // below. Pre-pull (hang-armed) shows a callout instead of the
  // timer/gauge — for hangs, the prescribed load; for BORK, a
  // "Pull MAX" prompt with no target. Once the auto-detect catches
  // the pull, hang-active replaces with the timer/gauge.
  if (phase === "hang-armed" || phase === "hang-active") {
    const isBork = currentStep.type === "bork";
    const target = isBork ? currentStep.holdSec : currentStep.targetSec;
    // BORK has no target load — force gauge runs without a target
    // marker, the user just pulls max. The "expected MVC" reference
    // appears on the pre-pull callout for context.
    const targetKg = isBork ? null : currentStep.targetLoadKg;
    const subtitleR = isBork
      ? `Rep ${borkRepIdx + 1} of ${currentStep.reps}`
      : "Both Hands";
    return (
      <Card>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline", marginBottom: 12 }}>
          <div style={{ fontSize: 11, color: C.muted, letterSpacing: 0.5, textTransform: "uppercase" }}>
            Step {stepIdx + 1} of {steps.length} · {currentStep.intensityLabel}
          </div>
          <div style={{ fontSize: 11, color: C.muted, fontWeight: 600 }}>
            <span style={{ color: GRIP_COLORS[currentStep.grip] }}>{currentStep.grip}</span> · {subtitleR}
          </div>
        </div>
        <div style={{ fontSize: 22, fontWeight: 800, marginBottom: 10 }}>{currentStep.title}</div>

        {phase === "hang-armed" ? (
          // Pre-pull callout. Hangs show a target load; BORK shows
          // "Pull MAX" with the expected MVC ballpark as a hint.
          <div style={{
            background: C.bg, border: `1px solid ${C.border}`,
            borderRadius: 12, padding: "20px 16px", marginBottom: 12,
            textAlign: "center",
          }}>
            <div style={{ fontSize: 11, color: C.muted, letterSpacing: 0.5, textTransform: "uppercase", marginBottom: 6 }}>
              {isBork ? "Pull MAX" : "Pull to begin"}
            </div>
            <div style={{ fontSize: 44, fontWeight: 900, color: C.purple, lineHeight: 1, fontVariantNumeric: "tabular-nums" }}>
              {isBork
                ? "MVC"
                : `${fmtW(currentStep.targetLoadKg, unit)} ${unit}`}
            </div>
            <div style={{ fontSize: 12, color: C.muted, marginTop: 6 }}>
              {isBork
                ? `hold ~${target}s as hard as possible`
                : `hold for ${target}s`}
              {isBork && currentStep.referenceMvcKg > 0 && (
                <span> · ~{fmtW(currentStep.referenceMvcKg, unit)} {unit} reference</span>
              )}
            </div>
            {/* Live force readout while armed but not yet pulling, so
                the user can confirm the Tindeq is reading and tare if
                needed. Number stays gray until the pull-detect fires. */}
            {tindeq?.connected && (
              <div style={{ marginTop: 14, fontSize: 12, color: C.muted }}>
                Live: <b style={{
                  color: C.text, fontVariantNumeric: "tabular-nums",
                }}>{fmtW(tindeq.force, unit)} {unit}</b>
              </div>
            )}
          </div>
        ) : (
          // Active hold — same primitives as finger training.
          <>
            <BigTimer
              seconds={elapsed}
              targetSeconds={target}
              running={true}
            />
            {tindeq?.connected ? (
              <ForceGauge
                force={tindeq.force}
                avg={tindeq.avgForce}
                peak={tindeq.peak}
                targetKg={targetKg}
                unit={unit}
              />
            ) : (
              <div style={{ fontSize: 12, color: C.muted, textAlign: "center", marginTop: 8 }}>
                Tindeq disconnected — release when target hold time is reached.
              </div>
            )}
          </>
        )}

        <div style={{ display: "flex", gap: 10, marginTop: 12 }}>
          <Btn onClick={skipStep} color={C.border} small>Skip step</Btn>
          <div style={{ flex: 1 }} />
          <Btn onClick={onClose} color={C.border} small>End</Btn>
        </div>
      </Card>
    );
  }

  // ── RENDER: REST ──
  if (phase === "rest") {
    const nextStep = steps[stepIdx + 1];
    const isMidPullupSet = currentStep?.type === "pullup" && (currentStep.sets || 1) > setIdx + 1;
    return (
      <Card>
        <div style={{ fontSize: 11, color: C.muted, letterSpacing: 0.5, textTransform: "uppercase", marginBottom: 8 }}>
          Rest
        </div>
        <div style={{
          background: C.bg, border: `1px solid ${C.border}`,
          borderRadius: 12, padding: "20px 16px", marginBottom: 16,
          textAlign: "center",
        }}>
          <div style={{ fontSize: 56, fontWeight: 900, color: C.blue, lineHeight: 1, fontVariantNumeric: "tabular-nums" }}>
            {fmtSec(restRemaining)}
          </div>
          <div style={{ fontSize: 12, color: C.muted, marginTop: 6 }}>seconds remaining</div>
        </div>
        <div style={{ fontSize: 12, color: C.muted, marginBottom: 16, lineHeight: 1.5 }}>
          {isMidPullupSet ? (
            <>Next: <b style={{ color: C.text }}>set {setIdx + 2} of {currentStep.sets}</b>.</>
          ) : nextStep ? (
            <>Up next: <b style={{ color: C.text }}>{nextStep.title}</b> · {nextStep.intensityLabel}.</>
          ) : (
            <>Final step coming up.</>
          )}
        </div>
        <div style={{ display: "flex", gap: 10 }}>
          <Btn onClick={advanceFromRest} color={C.blue}>Skip rest</Btn>
          <div style={{ flex: 1 }} />
          <Btn onClick={onClose} color={C.border} small>End</Btn>
        </div>
      </Card>
    );
  }

  // ── RENDER: PULLUP ──
  if (phase === "pullup") {
    const setsTotal = currentStep.sets || 1;
    return (
      <Card>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline", marginBottom: 12 }}>
          <div style={{ fontSize: 11, color: C.muted, letterSpacing: 0.5, textTransform: "uppercase" }}>
            Step {stepIdx + 1} of {steps.length} · Set {setIdx + 1} of {setsTotal}
          </div>
          <div style={{ fontSize: 11, color: C.muted }}>BW {protocol.bodyWeightLbs} lbs</div>
        </div>
        <div style={{ fontSize: 22, fontWeight: 800, marginBottom: 10 }}>{currentStep.title}</div>
        <div style={{ fontSize: 12, color: C.muted, marginBottom: 16, lineHeight: 1.5 }}>
          {currentStep.description}
        </div>
        <div style={{
          background: C.bg, border: `1px solid ${C.border}`,
          borderRadius: 12, padding: "20px 16px", marginBottom: 16,
          textAlign: "center",
        }}>
          <div style={{ fontSize: 11, color: C.muted, letterSpacing: 0.5, textTransform: "uppercase", marginBottom: 6 }}>Reps</div>
          <div style={{
            fontSize: 64, fontWeight: 900,
            color: pullupReps >= currentStep.targetReps ? C.green : C.purple,
            lineHeight: 1, fontVariantNumeric: "tabular-nums",
          }}>
            {pullupReps}
          </div>
          <div style={{ fontSize: 12, color: C.muted, marginTop: 6 }}>
            target {currentStep.targetReps}
          </div>
          <div style={{ display: "flex", gap: 10, marginTop: 14, justifyContent: "center" }}>
            <Btn onClick={() => setPullupReps(r => Math.max(0, r - 1))} color={C.border} small>−</Btn>
            <Btn onClick={() => setPullupReps(r => r + 1)} color={C.green}>+1 rep</Btn>
          </div>
        </div>
        <div style={{ display: "flex", gap: 10 }}>
          <Btn onClick={completePullupSet} color={C.blue}>
            {setIdx + 1 < setsTotal ? "Set done" : "Done"}
          </Btn>
          <Btn onClick={skipStep} color={C.border} small>Skip</Btn>
          <div style={{ flex: 1 }} />
          <Btn onClick={onClose} color={C.border} small>End</Btn>
        </div>
      </Card>
    );
  }

  // ── RENDER: DONE ──
  if (phase === "done") {
    return (
      <Card>
        <div style={{ fontSize: 22, fontWeight: 800, marginBottom: 8, color: C.green }}>
          ✓ Warm-up complete
        </div>
        <div style={{ fontSize: 13, color: C.text, lineHeight: 1.6, marginBottom: 16 }}>
          Forearms primed, fingers awake, neither flash-pumped nor under-cooked. The video calls for ~10 minutes of full rest now to clear fatigue, then you're ready for early goes.
        </div>
        <div style={{ fontSize: 12, color: C.muted, marginBottom: 16, lineHeight: 1.5, fontStyle: "italic" }}>
          Nothing here was logged — warm-up reps don't update the force curve.
        </div>
        <Btn onClick={onClose} color={C.green}>Close</Btn>
      </Card>
    );
  }

  return null;
}

export default WarmupView;
