import { Toggle } from '../ui/Toggle.jsx';
import { PeakTestView } from './PeakTestView.jsx';
import { TindeqBattery } from "./cards/TindeqBattery.jsx";
// ─────────────────────────────────────────────────────────────
// ADAPTIVE WARM-UP VIEW (Tindeq-driven)
// ─────────────────────────────────────────────────────────────
// Walks the user through the warm-up protocol generated by
// src/model/warmup.js. Two protocol modes:
//
//   - boulder: perfusion holds and two heavier strength ramps
//   - route: 45s perfusion holds and two lighter strength ramps
// Both modes optionally finish with a single-handed Peak Test.
//
// The preview screen offers a pill toggle between modes; selection
// persists in localStorage via LS_WARMUP_MODE_KEY.
//
// Hang step lifecycle:
//   - User pulls; force-threshold auto-detect (≥4 kg) triggers the
//     hold timer.
//   - The hold timer counts up; ForceGauge shows live force vs target.
//   - At targetSec, the rep auto-advances (endRepAndRequireRelease
//     blocks the next pull-detect until force drops, so the user's
//     continued grip doesn't immediately retrigger).
//   - Early release also ends the rep via auto-detect onRepEnd.
//
// Between Crusher and Micro steps, prompt the user to swap the
// Tindeq to the other gripper.
//
//
// State machine:
//   preview        — protocol overview, mode toggle, Start button
//   needs-tindeq   — Tindeq not connected, ask user to connect first
//   swap-prompt    — between Crusher and Micro: "Swap Tindeq to Micro"
//   hang-armed     — auto-detect armed, waiting for user to pull
//   hang-active    — hold timer counting up (force ≥ 4 kg)
//   rest           — countdown timer between steps
//   peak-test      — optional shared single-handed Peak Test flow
//   done           — completion

import React, { useEffect, useMemo, useRef, useState } from "react";
import { Card, Btn } from "../ui/components.jsx";
import { C } from "../ui/theme.js";
import { fmtW } from "../ui/format.js";
import { GRIP_COLORS } from "../ui/grip-colors.js";
import { generateWarmupProtocol } from "../model/warmup.js";
import { loadLS, saveLS, LS_WARMUP_MODE_KEY } from "../lib/storage.js";
// Shared live force display, with a consistent warm-up timer for holds and rest.
import { ForceGauge } from "./cards/LiveForceCard.jsx";

function fmtSec(s) {
  if (s == null || !isFinite(s)) return "0";
  const sec = Math.max(0, Math.round(s));
  if (sec < 60) return `${sec}`;
  return `${Math.floor(sec / 60)}:${String(sec % 60).padStart(2, "0")}`;
}

// Keep stage identity and timer placement stable throughout the warm-up.
function WarmupStage({ step, index, total, detail, children }) {
  return <Card>
    <div style={{ display: "flex", justifyContent: "space-between", flexWrap: "wrap", gap: 6, marginBottom: 12, color: C.muted, fontSize: 13 }}>
      <span>Warm-up · Step {index + 1} of {total}</span>
      <span style={{ color: GRIP_COLORS[step?.grip] || C.muted }}>{detail || "Both hands"}</span>
    </div>
    <div style={{ fontSize: 22, fontWeight: 800, marginBottom: 6 }}>{step?.title}</div>
    <div style={{ fontSize: 13, color: C.muted, marginBottom: 16 }}>{step?.intensityLabel}</div>
    {children}
  </Card>;
}

function WarmupTime({ seconds, label, target }) {
  return <div style={{ textAlign: "center", padding: "16px 0" }}>
    <div style={{ fontSize: 14, color: C.muted, marginBottom: 8 }}>{label}</div>
    <div role="timer" aria-label={label} style={{ fontSize: "clamp(56px, 17vw, 88px)", fontWeight: 800, color: C.blue, lineHeight: 1, fontVariantNumeric: "tabular-nums" }}>{fmtSec(seconds)}</div>
    <div style={{ marginTop: 10, fontSize: 14, color: C.muted }}>{target ? `of ${target} seconds` : "remaining"}</div>
  </div>;
}

export function WarmupView({ visible = true, history, bodyWeightKg, tindeq, unit = "lbs", onClose, addReps }) {
  // ── Warmup mode (boulder / route) ──
  // Persisted to LS so the user's last choice carries across sessions.
  // Default to "boulder" when no prior mode has been selected.
  const [mode, setMode] = useState(() => {
    const saved = loadLS(LS_WARMUP_MODE_KEY);
    return saved === "route" ? "route" : "boulder";
  });
  const updateMode = (next) => {
    setMode(next);
    saveLS(LS_WARMUP_MODE_KEY, next);
  };

  const [peakTestGrips, setPeakTestGrips] = useState([]);
  const includePeakTest = peakTestGrips.length > 0;
  const [frozenProtocol, setFrozenProtocol] = useState(null);
  const previewProtocol = useMemo(
    () => generateWarmupProtocol({ history, bodyWeightKg, mode, peakTestGrips }),
    [history, bodyWeightKg, mode, peakTestGrips]
  );

  const protocol = frozenProtocol || previewProtocol;

  // ── State machine ──
  const [phase, setPhase] = useState("preview"); // preview|needs-tindeq|swap-prompt|hang-armed|hang-active|rest|done
  const phaseRef = useRef(phase);
  const changePhase = (next) => {
    // BLE callbacks may arrive together before React renders. Transition
    // synchronously so a late release cannot complete the same rep twice.
    phaseRef.current = next;
    setPhase(next);
  };
  const [stepIdx, setStepIdx] = useState(0);
  // Each warmup hang is a single two-handed pull (titles literally
  // say "Two-Handed Crusher" / "Two-Handed Micro"). An earlier version
  // tracked activeHand and alternated L → R within a step; that's
  // been removed since the protocol's intent is one bilateral hold
  // per step.
  const [elapsed, setElapsed] = useState(0);          // sec since hang started
  const [restRemaining, setRestRemaining] = useState(0);
  const tickRef = useRef(null);
  const startTimeRef = useRef(null);

  // Hoisted above the effects below so the auto-detect wiring can
  // reference `currentStep` in its dep array without tripping
  // no-use-before-define. `steps` is read from `protocol.steps` but
  // guarded — the protocol can be ok:false, in which case the early
  // return below renders the can't-generate card and steps stays
  // an empty array. The effects skip work when there's no step.
  const steps = protocol.ok ? protocol.steps : [];
  const currentStep = steps[stepIdx];

  // ── Hang timer (count up while force is held above threshold) ──
  // The hang phase auto-advances when elapsed reaches the prescribed
  // targetSec — same intent as the rest countdown auto-advancing at
  // 0. Without this, the warmup just *suggests* a 30s hold and waits
  // for the user to release; with it, the protocol enforces the
  // prescribed schedule. If the user releases before target, the
  // auto-detect rep-end still fires (handleHangComplete from the BLE
  // callback), so an early release is graceful, not blocked.
  //
  // When auto-end fires while the user is still pulling, we also tell
  // the Tindeq to require a real release before re-arming pull-detect
  // (see tindeq.endRepAndRequireRelease). A continued pull must not
  // trigger the next rep before the athlete has released.
  useEffect(() => {
    if (tickRef.current) clearInterval(tickRef.current);
    if (phase === "hang-active") {
      const targetSec = currentStep?.targetSec || 0;
      startTimeRef.current = Date.now();
      setElapsed(0);
      tickRef.current = setInterval(() => {
        if (phaseRef.current !== "hang-active") return;
        const ms = Date.now() - startTimeRef.current;
        const secs = Math.floor(ms / 1000);
        setElapsed(secs);
        // Auto-advance once we've held to target. Check on the
        // millisecond clock (not `secs`) so a tick that lands a
        // hair past target still fires — setInterval drift can
        // skip a 1s boundary otherwise.
        if (targetSec > 0 && ms >= targetSec * 1000) {
          clearInterval(tickRef.current);
          tickRef.current = null;
          if (tindeq?.endRepAndRequireRelease) {
            tindeq.endRepAndRequireRelease();
          }
          handleHangComplete();
        }
      }, 200);
    } else if (phase === "rest") {
      const startedAt = Date.now();
      const restSec = currentStep?.restAfterSec || 60;
      setRestRemaining(restSec);
      tickRef.current = setInterval(() => {
        if (phaseRef.current !== "rest") return;
        const remaining = restSec - Math.floor((Date.now() - startedAt) / 1000);
        setRestRemaining(Math.max(0, remaining));
        if (remaining <= 0) {
          clearInterval(tickRef.current);
          advanceFromRest();
        }
      }, 200);
    }
    return () => {
      if (tickRef.current) clearInterval(tickRef.current);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [phase, stepIdx]);

  // Keep notifications running through rest and gripper changes. Stopping
  // after a timed hold hides the release from the sensor hook, leaving its
  // release guard armed when the athlete starts the next rep.
  const onRepStartRef = useRef(null);
  const onRepEndRef = useRef(null);
  onRepStartRef.current = () => {
    if (phaseRef.current === "hang-armed") changePhase("hang-active");
    else tindeq?.endRepAndRequireRelease?.(); // handling gear/rest is not a rep
  };
  onRepEndRef.current = (stats) => {
    if (phaseRef.current !== "hang-active") return;
    if (stats?.endReason === "equipment_interruption") {
      changePhase("interrupted");
      return;
    }
    handleHangComplete();
  };
  const inSensorPhase = ["hang-armed", "hang-active", "rest", "swap-prompt", "interrupted"].includes(phase)
    && currentStep?.type === "hang";
  useEffect(() => {
    if (!visible || !tindeq?.connected || !inSensorPhase) return;
    let disposed = false;
    Promise.resolve(tindeq.startAutoDetect(
      () => onRepStartRef.current?.(),
      stats => onRepEndRef.current?.(stats),
      { endOnTargetDrop: false },
    )).catch(() => { if (!disposed) changePhase("interrupted"); });
    return () => {
      disposed = true;
      Promise.resolve(tindeq.stopAutoDetect()).catch(() => {});
      tindeq.targetKgRef.current = null;
    };
    // The hook's methods are stable; changing phase/step must not restart BLE.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [visible, inSensorPhase, tindeq?.connected]);

  useEffect(() => {
    if (visible && tindeq && inSensorPhase) tindeq.targetKgRef.current = currentStep?.targetLoadKg ?? null;
  }, [visible, tindeq, inSensorPhase, currentStep]);

  useEffect(() => {
    if ((!visible || !tindeq?.connected) && phaseRef.current === "hang-active") changePhase("interrupted");

  }, [visible, tindeq?.connected]);

  if (!protocol.ok) {
    return (
      <Card>
        <div style={{ fontSize: 18, fontWeight: 700, marginBottom: 8 }}>Adaptive Warm-up</div>
        <div style={{ fontSize: 13, color: C.yellow, marginBottom: 12, lineHeight: 1.5 }}>
          ⚠ Can't generate yet
        </div>
        <div style={{ fontSize: 13, color: C.text, lineHeight: 1.6, marginBottom: 16 }}>
          {protocol.reason}
        </div>
        <Btn onClick={onClose} small>Back</Btn>
      </Card>
    );
  }

  // (steps + currentStep hoisted above the effects — see comment up top.)

  // ── Flow control ──
  // Each warmup hang is a single two-handed hold (the steps are titled
  // "Two-Handed Crusher" / "Two-Handed Micro"). Earlier versions did
  // separate L then R reps per step; that's been removed — one pull,
  // one hold, advance to rest.
  function startProtocol() {
    if (!tindeq?.connected) {
      changePhase("needs-tindeq");
      return;
    }
    setFrozenProtocol(previewProtocol);
    setStepIdx(0);
    enterStep(0);
  }

  function enterStep(idx) {
    const step = steps[idx];
    if (!step) {
      changePhase("done");
      return;
    }
    const prevGrip = steps[idx - 1]?.grip;
    if (prevGrip && prevGrip !== step.grip) {
      changePhase("swap-prompt");
    } else if (step.type === "hang") {
      changePhase("hang-armed");
    } else if (step.type === "peak_test") {
      changePhase("peak-test");
    }
  }

  // A timed hold or early release advances to rest, except after the final step.
  function handleHangComplete() {
    if (phaseRef.current !== "hang-active") return;
    setElapsed(0);
    const isLastStep = stepIdx >= steps.length - 1;
    if (!isLastStep && currentStep?.restAfterSec > 0) {
      changePhase("rest");
    } else {
      advanceToNextStep();
    }
  }

  function advanceFromRest() {
    if (phaseRef.current !== "rest") return;
    advanceToNextStep();
  }

  function advanceToNextStep() {
    const next = stepIdx + 1;
    if (next >= steps.length) {
      changePhase("done");
      setStepIdx(next);
    } else {
      setStepIdx(next);
      enterStep(next);
    }
  }

  function skipStep() {
    tindeq?.endRepAndRequireRelease?.();
    advanceToNextStep();
  }

  function confirmSwap() {
    // The new grip may begin a two-handed hold or its single-hand test.
    changePhase(currentStep.type === "peak_test" ? "peak-test" : "hang-armed");
  }

  // ── RENDER: PREVIEW ──
  if (phase === "preview") {
    const tindeqConnected = !!tindeq?.connected;
    const tindeqReconnecting = !!tindeq?.reconnecting;
    // Mode toggle helper — mirrors the discipline pill pattern from
    // ClimbingAnalysisView so the warmup card feels visually
    // consistent with the rest of the app.
    const modePill = (key, label, desc) => {
      const active = mode === key;
      return (
        <button
          key={key}
          onClick={() => updateMode(key)}
          style={{
            flex: 1, padding: "8px 10px", borderRadius: 10,
            background: active ? C.purple : C.bg,
            color: active ? "#fff" : C.muted,
            border: `1px solid ${active ? C.purple : C.border}`,
            fontWeight: active ? 700 : 500, fontSize: 13, cursor: "pointer",
            textAlign: "center", lineHeight: 1.2,
          }}
          title={desc}
        >
          {label}
        </button>
      );
    };
    return (
      <Card>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline", marginBottom: 6 }}>
          <div style={{ fontSize: 18, fontWeight: 800 }}>Adaptive Warm-up</div>
          <div style={{ fontSize: 11, color: C.muted }}>BW {protocol.bodyWeightLbs} lbs</div>
        </div>
        <div style={{ fontSize: 12, color: C.muted, marginBottom: 12, lineHeight: 1.5 }}>
          Timed two-handed holds, progressing from lighter to heavier loads.
          {includePeakTest && " Includes your selected single-handed Peak Tests after the ramps."}
          {" Connect the Crusher first; you'll be prompted to swap to the Micro mid-warmup."}
        </div>
        {protocol.estimatedGrips?.length > 0 && <p role="status" style={{ color: C.yellow }}>
          {protocol.estimatedGrips.join(" and ")} loads are estimates from manually logged workouts. Adjust them to a comfortable warmup effort.
        </p>}
        {/* Mode toggle: boulder or route ramp intensity and perfusion duration.
            Persists to LS_WARMUP_MODE_KEY. */}
        <div style={{ display: "flex", gap: 8, marginBottom: 16 }}>
          {modePill("boulder", "🪨 Bouldering", "Progressive holds and two strength ramps.")}
          {modePill("route", "🧗 Routes", "Progressive holds and two lighter strength ramps.")}
        </div>
        {['Crusher', 'Micro'].map(grip => <Toggle key={grip} label={`${grip} Max Test`}
          checked={peakTestGrips.includes(grip)} disabled={!protocol.availablePeakGrips?.includes(grip)}
          onChange={checked => setPeakTestGrips(grips => checked ? [...grips, grip] : grips.filter(g => g !== grip))} />)}
        {includePeakTest && <p style={{ color: C.muted }}>Three 3-second pulls per hand, alternating hands. Rest 60 seconds between rounds. Only the test measurements are saved.</p>}
        <div style={{ marginBottom: 16 }}>
          {steps.map((s, i) => (
            <div key={s.id} style={{
              display: "flex", justifyContent: "space-between", alignItems: "center",
              padding: "10px 0",
              borderBottom: i < steps.length - 1 ? `1px solid ${C.border}` : "none",
            }}>
              <div style={{ flex: 1 }}>
                <div style={{ fontSize: 11, color: C.muted, marginBottom: 2 }}>Step {i + 1}</div>
                <div style={{ fontSize: 14, fontWeight: 600, color: C.text }}>{s.title}</div>
                <div style={{ fontSize: 11, color: C.muted, marginTop: 2 }}>
                  {s.intensityLabel}
                  {i < steps.length - 1 && s.restAfterSec > 0 && ` · rest ${fmtSec(s.restAfterSec)}s`}
                </div>
              </div>
              <div style={{ textAlign: "right", marginLeft: 12 }}>
                {s.type === "hang" ? (
                  <>
                    <div style={{ fontSize: 22, fontWeight: 800, color: C.purple, lineHeight: 1, fontVariantNumeric: "tabular-nums" }}>
                      {fmtW(s.targetLoadKg, unit)}
                    </div>
                    <div style={{ fontSize: 10, color: C.muted, marginTop: 2 }}>
                      {unit} · {s.targetSec}s
                    </div>
                  </>
                ) : s.type === "peak_test" ? <b>3 × L/R</b> : null}
              </div>
            </div>
          ))}
        </div>
        <div style={{ fontSize: 11, color: C.muted, marginBottom: 12, lineHeight: 1.5, fontStyle: "italic" }}>
          {includePeakTest ? "Only Peak Test measurements are saved. Warmup holds are not logged." : "Nothing here gets logged as training data."}
        </div>

        {/* Tindeq connect row — placed directly above the Start button
            so the connection prerequisite reads as a step you take
            right before tapping Start. Mirrors the connect card on
            Session Setup but condensed for inline use. */}
        <div style={{
          background: C.bg, border: `1px solid ${C.border}`,
          borderRadius: 10, padding: "10px 12px", marginBottom: 12,
        }}>
          <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
            <div style={{ flex: 1, minWidth: 0 }}>
              <div style={{ fontSize: 13, fontWeight: 600 }}>Tindeq Progressor</div>
              <div style={{ fontSize: 11, color: tindeqConnected ? C.green : C.muted }}>
                {tindeqConnected
                  ? "Connected ✓"
                  : tindeqReconnecting
                    ? "Reconnecting…"
                    : tindeq?.bleError || "Not connected"}
              </div>
            </div>
            <div style={{ display: "flex", gap: 8 }}>
              {tindeqConnected && (
                <Btn small onClick={tindeq.tare} color={C.muted}>Tare</Btn>
              )}
              <Btn
                small
                onClick={() => tindeq?.connect?.()}
                disabled={tindeqConnected || tindeqReconnecting}
                color={tindeqConnected ? C.green : tindeqReconnecting ? C.orange : C.blue}
              >
                {tindeqConnected ? "Connected" : tindeqReconnecting ? "Reconnecting…" : "Connect Tindeq"}
              </Btn>
            </div>
          </div>
          <TindeqBattery battery={tindeq?.battery} connected={tindeqConnected} />
          {tindeqConnected && (
            <div style={{ marginTop: 6, fontSize: 11, color: C.muted }}>
              Live force: <b style={{ color: C.blue }}>{fmtW(tindeq.force, unit)} {unit}</b> · tap Tare to zero before starting.
            </div>
          )}
        </div>

        <div style={{ display: "flex", gap: 10 }}>
          <Btn
            onClick={startProtocol}
            color={C.green}
            disabled={!tindeqConnected}
          >
            Start
          </Btn>
          <Btn onClick={onClose} color={C.border} small>Back</Btn>
        </div>
      </Card>
    );
  }

  if (phase === 'peak-test') {
    return <PeakTestView key={currentStep.id} visible={visible} grip={currentStep.grip} history={history} tindeq={tindeq}
      addReps={addReps} unit={unit} source="warmup" onClose={advanceToNextStep}
      completionLabel={stepIdx < steps.length - 1 ? 'Continue warm-up' : 'Finish warm-up'} />;
  }

  // ── RENDER: NEEDS-TINDEQ (fallback for mid-warmup disconnect) ──
  if (phase === "needs-tindeq") {
    return (
      <Card>
        <div style={{ fontSize: 18, fontWeight: 700, marginBottom: 8 }}>Connect the Tindeq</div>
        <div style={{ fontSize: 13, color: C.text, lineHeight: 1.6, marginBottom: 16 }}>
          The warm-up uses real-time force feedback to hit prescribed loads. Connect your Tindeq (with the Crusher gripper attached), then come back and tap Start.
        </div>
        <Btn onClick={() => changePhase("preview")} small>Back to preview</Btn>
      </Card>
    );
  }

  const stageDetail = `${currentStep?.grip} · ${currentStep?.type === 'peak_test' ? 'Single-handed' : 'Both hands'}`;
  const stage = children => <WarmupStage step={currentStep} index={stepIdx} total={steps.length} detail={stageDetail}><TindeqBattery battery={tindeq?.battery} connected={tindeq?.connected} warningOnly />{children}</WarmupStage>;
  const actions = (primary, skip = true) => <div style={{ display: "flex", flexWrap: "wrap", gap: 10, marginTop: 16 }}>
    {primary}
    {skip && <Btn onClick={skipStep} color={C.border}>Skip step</Btn>}
    <Btn onClick={onClose} color={C.border}>End warm-up</Btn>
  </div>;
  const connectionNotice = !tindeq?.connected && <div role="status" style={{ color: C.yellow, marginBottom: 12 }}>
    <p>{tindeq?.reconnecting ? "Reconnecting to Tindeq…" : "Connect the Tindeq to continue."}</p>
    <Btn onClick={() => tindeq?.connect?.()} disabled={tindeq?.reconnecting}>Connect Tindeq</Btn>
  </div>;

  if (phase === "swap-prompt") {
    return stage(<>
      <div style={{ fontSize: 20, fontWeight: 700, marginBottom: 12 }}>Swap to {currentStep.grip}</div>
      <p style={{ color: C.muted }}>Attach the Tindeq to the {currentStep.grip} gripper. Release the load, then tap Continue.</p>
      {connectionNotice}
      {actions(<Btn onClick={confirmSwap} color={C.green} disabled={!tindeq?.connected}>Continue</Btn>, false)}
    </>);
  }

  if (phase === "interrupted") {
    return stage(<>
      <div role="status" style={{ color: C.yellow, fontSize: 18, fontWeight: 700 }}>Warm-up paused</div>
      <p style={{ color: C.muted }}>The sensor stopped sending force readings. This rep has not been counted. Release the load, check the connection, then retry when ready.</p>
      {connectionNotice}
      {actions(<Btn onClick={() => { setElapsed(0); changePhase("hang-armed"); }} disabled={!tindeq?.connected}>Retry rep</Btn>)}
    </>);
  }

  if (phase === "hang-armed" || phase === "hang-active") {
    const target = currentStep.targetSec;
    const active = phase === "hang-active";
    return stage(<>
      <div style={{ fontSize: 15, textAlign: "center", color: C.text }}>
        {active ? "Hold until the timer finishes, then release." : "Pull to begin. The timer starts automatically."}
      </div>
      <WarmupTime seconds={active ? elapsed : 0} label={active ? "Hold time" : "Ready"} target={target} />
      {connectionNotice}
      <ForceGauge
        force={tindeq?.force || 0}
        avg={active ? tindeq?.avgForce || 0 : 0}
        peak={active ? tindeq?.peak || 0 : 0}
        targetKg={currentStep.targetLoadKg}
        maxDisplay={Math.max(50, (currentStep.targetLoadKg || 0) * 1.25)}
        numberSize="clamp(48px, 15vw, 88px)"
        unit={unit}
      />
      {actions()}
    </>);
  }

  if (phase === "rest") {
    const nextStep = steps[stepIdx + 1];
    return stage(<>
      <div style={{ fontSize: 15, textAlign: "center" }}>Release and rest.</div>
      <WarmupTime seconds={restRemaining} label="Rest" />
      <div style={{ color: C.muted, lineHeight: 1.6, textAlign: "center" }}>
        {nextStep && <div>Up next: <b style={{ color: C.text }}>{nextStep.title}</b></div>}
        {nextStep?.type === "hang" && <div style={{ fontSize: 22, fontWeight: 700, color: C.blue }}>{fmtW(nextStep.targetLoadKg, unit)} {unit} · {nextStep.targetSec}s</div>}
      </div>
      {connectionNotice}
      {actions(<Btn onClick={advanceFromRest}>Skip rest</Btn>, false)}
    </>);
  }

  // ── RENDER: DONE ──
  if (phase === "done") {
    return (
      <Card>
        <div style={{ fontSize: 22, fontWeight: 800, marginBottom: 8, color: C.green }}>
          ✓ Warm-up complete
        </div>
        <div style={{ fontSize: 13, color: C.text, lineHeight: 1.6, marginBottom: 16 }}>
          Continue whenever you feel ready.
        </div>
        <div style={{ fontSize: 12, color: C.muted, marginBottom: 16, lineHeight: 1.5, fontStyle: "italic" }}>
          {includePeakTest ? 'Peak Test measurements were saved separately. Warmup holds do not update the force curve.' : 'Nothing here was logged — warm-up reps do not update the force curve.'}
        </div>
        <Btn onClick={onClose} color={C.green}>Close</Btn>
      </Card>
    );
  }

  return null;
}

export default WarmupView;
