// ─────────────────────────────────────────────────────────────
// ADAPTIVE WARM-UP VIEW (Tindeq-driven)
// ─────────────────────────────────────────────────────────────
// Walks the user through the warm-up protocol generated by
// src/model/warmup.js. Uses the Tindeq for hang steps:
//
//   - For each hang step: alternate L → R on a single Tindeq.
//   - User pulls into the gripper; force-threshold auto-detect (≥4 kg)
//     triggers the hold timer.
//   - Live force readout shows progress toward the target load.
//   - When the timer reaches the target hold duration, the display
//     turns green to signal release.
//   - User releases; auto-detect ends the rep; advance to next hand
//     or to rest.
//
// Between Crusher and Micro steps, prompt the user to swap the Tindeq
// to the other gripper.
//
// Pullup finisher uses a manual tap counter (no Tindeq).
//
// State machine:
//   preview        — protocol overview, Start button
//   needs-tindeq   — Tindeq not connected, ask user to connect first
//   swap-prompt    — between Crusher and Micro: "Swap Tindeq to Micro"
//   hang-armed     — auto-detect armed, waiting for user to pull
//   hang-active    — hold timer counting up (force ≥ 4 kg)
//   rest           — countdown timer between hands or steps
//   pullup         — tap counter for finisher reps
//   done           — completion

import React, { useEffect, useMemo, useRef, useState } from "react";
import { Card, Btn } from "../ui/components.js";
import { C } from "../ui/theme.js";
import { fmtW } from "../ui/format.js";
import { generateWarmupProtocol } from "../model/warmup.js";

const GRIP_COLORS = { Micro: "#e05560", Crusher: C.orange, Prime: "#7c5cbf" };

function fmtSec(s) {
  if (s == null || !isFinite(s)) return "0";
  const sec = Math.max(0, Math.round(s));
  if (sec < 60) return `${sec}`;
  return `${Math.floor(sec / 60)}:${String(sec % 60).padStart(2, "0")}`;
}

// Compact live-force display showing current force, peak, and target.
// Colors green when within ±15% of target so the user sees they're
// at the prescribed load.
function ForceReadout({ force, peak, targetKg, unit = "lbs" }) {
  const inWindow = targetKg && Math.abs((force || 0) - targetKg) <= targetKg * 0.15;
  const display = (kg) => kg == null ? "—" : fmtW(kg, unit);
  return (
    <div style={{
      background: C.bg, border: `1px solid ${C.border}`,
      borderRadius: 10, padding: "12px 14px",
      display: "flex", justifyContent: "space-around", alignItems: "baseline",
    }}>
      <div style={{ textAlign: "center" }}>
        <div style={{ fontSize: 9, color: C.muted, letterSpacing: 0.5, textTransform: "uppercase", marginBottom: 2 }}>Now</div>
        <div style={{
          fontSize: 28, fontWeight: 800, lineHeight: 1,
          color: inWindow ? C.green : (force > 0 ? C.text : C.muted),
          fontVariantNumeric: "tabular-nums",
        }}>
          {display(force)}
        </div>
      </div>
      <div style={{ textAlign: "center" }}>
        <div style={{ fontSize: 9, color: C.muted, letterSpacing: 0.5, textTransform: "uppercase", marginBottom: 2 }}>Target</div>
        <div style={{
          fontSize: 28, fontWeight: 800, lineHeight: 1,
          color: C.purple,
          fontVariantNumeric: "tabular-nums",
        }}>
          {display(targetKg)}
        </div>
      </div>
      <div style={{ textAlign: "center" }}>
        <div style={{ fontSize: 9, color: C.muted, letterSpacing: 0.5, textTransform: "uppercase", marginBottom: 2 }}>Peak</div>
        <div style={{
          fontSize: 28, fontWeight: 800, lineHeight: 1,
          color: C.muted,
          fontVariantNumeric: "tabular-nums",
        }}>
          {display(peak)}
        </div>
      </div>
    </div>
  );
}

export function WarmupView({ history, wLog, bodyWeightKg, tindeq, unit = "lbs", onClose }) {
  const protocol = useMemo(
    () => generateWarmupProtocol({ history, wLog, bodyWeightKg }),
    [history, wLog, bodyWeightKg]
  );

  // ── State machine ──
  const [phase, setPhase] = useState("preview"); // preview|needs-tindeq|swap-prompt|hang-armed|hang-active|rest|pullup|done
  const [stepIdx, setStepIdx] = useState(0);
  const [activeHand, setActiveHand] = useState("L"); // L → R within a hang step
  const [setIdx, setSetIdx] = useState(0);            // for multi-set pullup
  const [pullupReps, setPullupReps] = useState(0);
  const [elapsed, setElapsed] = useState(0);          // sec since hang started
  const [restRemaining, setRestRemaining] = useState(0);

  const tickRef = useRef(null);
  const startTimeRef = useRef(null);

  // ── Hang timer (count up while force is held above threshold) ──
  useEffect(() => {
    if (tickRef.current) clearInterval(tickRef.current);
    if (phase === "hang-active") {
      startTimeRef.current = Date.now();
      setElapsed(0);
      tickRef.current = setInterval(() => {
        setElapsed(Math.floor((Date.now() - startTimeRef.current) / 1000));
      }, 200);
    } else if (phase === "rest") {
      const startedAt = Date.now();
      const restSec = currentStep?.restAfterSec || 60;
      setRestRemaining(restSec);
      tickRef.current = setInterval(() => {
        const remaining = restSec - Math.floor((Date.now() - startedAt) / 1000);
        setRestRemaining(Math.max(0, remaining));
        if (remaining <= 0) {
          clearInterval(tickRef.current);
          advanceFromRest();
        }
      }, 200);
    }
    return () => {
      if (tickRef.current) clearInterval(tickRef.current);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [phase, stepIdx, activeHand, setIdx]);

  // ── Tindeq auto-detect wiring ──
  // When phase is hang-armed or hang-active, register callbacks. Pull
  // start (force ≥ 4 kg) flips us to hang-active; pull end flips us to
  // rest (and advances the hand or step).
  useEffect(() => {
    if (!tindeq?.connected) return;
    const armed = phase === "hang-armed" || phase === "hang-active";
    if (!armed) return;
    tindeq.targetKgRef.current = currentStep?.targetLoadKg ?? null;
    tindeq.startAutoDetect(
      // onRepStart — user crossed pull threshold
      () => setPhase("hang-active"),
      // onRepEnd — user released. Don't pass any logged data — warm-up
      // reps don't get recorded. Just advance.
      () => handleHangComplete(),
    );
    return () => {
      tindeq.stopAutoDetect();
      tindeq.targetKgRef.current = null;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [phase, stepIdx, activeHand]);

  if (!protocol.ok) {
    return (
      <Card>
        <div style={{ fontSize: 18, fontWeight: 700, marginBottom: 8 }}>Adaptive Warm-up</div>
        <div style={{ fontSize: 13, color: C.yellow, marginBottom: 12, lineHeight: 1.5 }}>
          ⚠ Can't generate yet
        </div>
        <div style={{ fontSize: 13, color: C.text, lineHeight: 1.6, marginBottom: 16 }}>
          {protocol.reason}
        </div>
        <Btn onClick={onClose} small>Back</Btn>
      </Card>
    );
  }

  const steps = protocol.steps;
  const currentStep = steps[stepIdx];

  // ── Flow control ──
  function startProtocol() {
    if (!tindeq?.connected) {
      setPhase("needs-tindeq");
      return;
    }
    setStepIdx(0);
    setActiveHand("L");
    setSetIdx(0);
    setPullupReps(0);
    enterStep(0, "L");
  }

  function enterStep(idx, hand = "L") {
    const step = steps[idx];
    if (!step) {
      setPhase("done");
      return;
    }
    if (step.type === "hang") {
      // If switching from one grip to another (Crusher → Micro), insert
      // a swap-prompt before arming the next hang.
      const prevStep = steps[idx - 1];
      if (prevStep && prevStep.type === "hang" && prevStep.grip !== step.grip && hand === "L") {
        setPhase("swap-prompt");
      } else {
        setActiveHand(hand);
        setPhase("hang-armed");
      }
    } else if (step.type === "pullup") {
      setPullupReps(0);
      setPhase("pullup");
    }
  }

  // Called when the Tindeq auto-detect signals a rep has ended (user
  // released). Advance L → R within step, or move to rest after R.
  function handleHangComplete() {
    setElapsed(0);
    if (activeHand === "L") {
      // Move to right hand. Brief inter-hand pause uses the rest path
      // with a short 5s breather.
      setActiveHand("R");
      // Skip rest; go straight back to armed for the right hand.
      setPhase("hang-armed");
    } else {
      // Right hand done — rest before next step.
      if (stepIdx < steps.length - 1 && currentStep.restAfterSec > 0) {
        setPhase("rest");
      } else {
        advanceToNextStep();
      }
    }
  }

  function advanceFromRest() {
    if (currentStep?.type === "pullup" && (currentStep.sets || 1) > setIdx + 1) {
      setSetIdx(s => s + 1);
      setPullupReps(0);
      setPhase("pullup");
      return;
    }
    advanceToNextStep();
  }

  function advanceToNextStep() {
    const next = stepIdx + 1;
    setActiveHand("L");
    setSetIdx(0);
    setPullupReps(0);
    if (next >= steps.length) {
      setPhase("done");
      setStepIdx(next);
    } else {
      setStepIdx(next);
      enterStep(next, "L");
    }
  }

  function completePullupSet() {
    const nSets = currentStep.sets || 1;
    if (setIdx + 1 < nSets) {
      setPhase("rest");
    } else {
      advanceToNextStep();
    }
  }

  function skipStep() {
    advanceToNextStep();
  }

  function confirmSwap() {
    // After swap-prompt, move on into the hang for the new grip, left hand.
    setActiveHand("L");
    setPhase("hang-armed");
  }

  // ── RENDER: PREVIEW ──
  if (phase === "preview") {
    const tindeqConnected = !!tindeq?.connected;
    const tindeqReconnecting = !!tindeq?.reconnecting;
    return (
      <Card>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline", marginBottom: 6 }}>
          <div style={{ fontSize: 18, fontWeight: 800 }}>Adaptive Warm-up</div>
          <div style={{ fontSize: 11, color: C.muted }}>BW {protocol.bodyWeightLbs} lbs</div>
        </div>
        <div style={{ fontSize: 12, color: C.muted, marginBottom: 16, lineHeight: 1.5 }}>
          Tindeq-driven. Loads come from your force curves; targets are short, sub-failure holds. Same intensity for every user, every session. Connect the Crusher first; you'll be prompted to swap to the Micro mid-warmup.
        </div>

        {/* Tindeq connect row — same shape as the connect card on the
            Setup page, condensed to fit inside the preview. The user
            can connect / tare here before starting so they don't get
            redirected to a separate connection screen mid-flow. */}
        <div style={{
          background: C.bg, border: `1px solid ${C.border}`,
          borderRadius: 10, padding: "10px 12px", marginBottom: 16,
        }}>
          <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
            <div style={{ flex: 1, minWidth: 0 }}>
              <div style={{ fontSize: 13, fontWeight: 600 }}>Tindeq Progressor</div>
              <div style={{ fontSize: 11, color: tindeqConnected ? C.green : C.muted }}>
                {tindeqConnected
                  ? "Connected ✓"
                  : tindeqReconnecting
                    ? "Reconnecting…"
                    : tindeq?.bleError || "Not connected"}
              </div>
            </div>
            <div style={{ display: "flex", gap: 8 }}>
              {tindeqConnected && (
                <Btn small onClick={tindeq.tare} color={C.muted}>Tare</Btn>
              )}
              <Btn
                small
                onClick={() => tindeq?.connect?.()}
                disabled={tindeqConnected || tindeqReconnecting}
                color={tindeqConnected ? C.green : tindeqReconnecting ? C.orange : C.blue}
              >
                {tindeqConnected ? "Connected" : tindeqReconnecting ? "Reconnecting…" : "Connect BLE"}
              </Btn>
            </div>
          </div>
          {tindeqConnected && (
            <div style={{ marginTop: 6, fontSize: 11, color: C.muted }}>
              Live force: <b style={{ color: C.blue }}>{fmtW(tindeq.force, unit)} {unit}</b> · tap Tare to zero before starting.
            </div>
          )}
        </div>
        <div style={{ marginBottom: 16 }}>
          {steps.map((s, i) => (
            <div key={s.id} style={{
              display: "flex", justifyContent: "space-between", alignItems: "center",
              padding: "10px 0",
              borderBottom: i < steps.length - 1 ? `1px solid ${C.border}` : "none",
            }}>
              <div style={{ flex: 1 }}>
                <div style={{ fontSize: 11, color: C.muted, marginBottom: 2 }}>Step {i + 1}</div>
                <div style={{ fontSize: 14, fontWeight: 600, color: C.text }}>{s.title}</div>
                <div style={{ fontSize: 11, color: C.muted, marginTop: 2 }}>
                  {s.intensityLabel}
                  {i < steps.length - 1 && ` · rest ${fmtSec(s.restAfterSec)}s`}
                </div>
              </div>
              <div style={{ textAlign: "right", marginLeft: 12 }}>
                {s.type === "hang" ? (
                  <>
                    <div style={{ fontSize: 22, fontWeight: 800, color: C.purple, lineHeight: 1, fontVariantNumeric: "tabular-nums" }}>
                      {fmtW(s.targetLoadKg, unit)}
                    </div>
                    <div style={{ fontSize: 10, color: C.muted, marginTop: 2 }}>
                      {unit} · {s.targetSec}s
                    </div>
                  </>
                ) : (
                  <>
                    <div style={{ fontSize: 22, fontWeight: 800, color: C.purple, lineHeight: 1 }}>
                      {s.targetReps}×{s.sets || 1}
                    </div>
                    <div style={{ fontSize: 10, color: C.muted, marginTop: 2 }}>reps × sets</div>
                  </>
                )}
              </div>
            </div>
          ))}
        </div>
        <div style={{ fontSize: 11, color: C.muted, marginBottom: 12, lineHeight: 1.5, fontStyle: "italic" }}>
          Pullup count: {protocol.pullupSource.sourceText}
          {protocol.pullupSource.count != null && ` (${protocol.pullupSource.count})`}.
          Nothing here gets logged as training data.
        </div>
        <div style={{ display: "flex", gap: 10 }}>
          <Btn
            onClick={startProtocol}
            color={C.green}
            disabled={!tindeqConnected}
          >
            Start
          </Btn>
          <Btn onClick={onClose} color={C.border} small>Back</Btn>
        </div>
        {!tindeqConnected && (
          <div style={{ fontSize: 11, color: C.muted, marginTop: 8, fontStyle: "italic" }}>
            Connect the Tindeq above before starting — the warm-up uses real-time force feedback to hit prescribed loads.
          </div>
        )}
      </Card>
    );
  }

  // ── RENDER: NEEDS-TINDEQ (fallback for mid-warmup disconnect) ──
  if (phase === "needs-tindeq") {
    return (
      <Card>
        <div style={{ fontSize: 18, fontWeight: 700, marginBottom: 8 }}>Connect the Tindeq</div>
        <div style={{ fontSize: 13, color: C.text, lineHeight: 1.6, marginBottom: 16 }}>
          The warm-up uses real-time force feedback to hit prescribed loads. Connect your Tindeq (with the Crusher gripper attached), then come back and tap Start.
        </div>
        <Btn onClick={() => setPhase("preview")} small>Back to preview</Btn>
      </Card>
    );
  }

  // ── RENDER: SWAP-PROMPT (between Crusher and Micro steps) ──
  if (phase === "swap-prompt") {
    return (
      <Card>
        <div style={{ fontSize: 11, color: C.muted, letterSpacing: 0.5, textTransform: "uppercase", marginBottom: 8 }}>
          Step {stepIdx + 1} of {steps.length}
        </div>
        <div style={{ fontSize: 22, fontWeight: 800, marginBottom: 10 }}>
          Swap to <span style={{ color: GRIP_COLORS[currentStep.grip] }}>{currentStep.grip}</span>
        </div>
        <div style={{ fontSize: 13, color: C.text, lineHeight: 1.6, marginBottom: 16 }}>
          Detach the Tindeq from the Crusher and attach it to the Micro gripper. Tap Continue when ready.
        </div>
        <div style={{ display: "flex", gap: 10 }}>
          <Btn onClick={confirmSwap} color={C.green}>Continue</Btn>
          <Btn onClick={onClose} color={C.border} small>End</Btn>
        </div>
      </Card>
    );
  }

  // ── RENDER: HANG (armed or active) ──
  if (phase === "hang-armed" || phase === "hang-active") {
    const target = currentStep.targetSec;
    const reached = elapsed >= target;
    const handLabel = activeHand === "L" ? "Left Hand" : "Right Hand";
    return (
      <Card>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline", marginBottom: 12 }}>
          <div style={{ fontSize: 11, color: C.muted, letterSpacing: 0.5, textTransform: "uppercase" }}>
            Step {stepIdx + 1} of {steps.length} · {currentStep.intensityLabel}
          </div>
          <div style={{ fontSize: 11, color: C.muted, fontWeight: 600 }}>
            <span style={{ color: GRIP_COLORS[currentStep.grip] }}>{currentStep.grip}</span> · {handLabel}
          </div>
        </div>
        <div style={{ fontSize: 22, fontWeight: 800, marginBottom: 10 }}>{currentStep.title}</div>

        {phase === "hang-armed" ? (
          <div style={{
            background: C.bg, border: `1px solid ${C.border}`,
            borderRadius: 12, padding: "20px 16px", marginBottom: 12,
            textAlign: "center",
          }}>
            <div style={{ fontSize: 11, color: C.muted, letterSpacing: 0.5, textTransform: "uppercase", marginBottom: 6 }}>
              Pull to begin
            </div>
            <div style={{ fontSize: 44, fontWeight: 900, color: C.purple, lineHeight: 1, fontVariantNumeric: "tabular-nums" }}>
              {fmtW(currentStep.targetLoadKg, unit)} {unit}
            </div>
            <div style={{ fontSize: 12, color: C.muted, marginTop: 6 }}>
              hold for {target}s
            </div>
          </div>
        ) : (
          <div style={{
            background: C.bg, border: `1px solid ${C.border}`,
            borderRadius: 12, padding: "20px 16px", marginBottom: 12,
            textAlign: "center",
          }}>
            <div style={{ fontSize: 11, color: C.muted, letterSpacing: 0.5, textTransform: "uppercase", marginBottom: 6 }}>
              {reached ? "Release when ready" : "Holding"}
            </div>
            <div style={{
              fontSize: 64, fontWeight: 900,
              color: reached ? C.green : C.purple,
              lineHeight: 1, fontVariantNumeric: "tabular-nums",
            }}>
              {fmtSec(elapsed)}s
            </div>
            <div style={{ fontSize: 12, color: C.muted, marginTop: 6 }}>
              target {target}s
              {reached && <span style={{ color: C.green, marginLeft: 8 }}>✓ done</span>}
            </div>
          </div>
        )}

        {tindeq?.connected && (
          <ForceReadout
            force={tindeq.force}
            peak={tindeq.peak}
            targetKg={currentStep.targetLoadKg}
            unit={unit}
          />
        )}

        <div style={{ display: "flex", gap: 10, marginTop: 12 }}>
          <Btn onClick={skipStep} color={C.border} small>Skip step</Btn>
          <div style={{ flex: 1 }} />
          <Btn onClick={onClose} color={C.border} small>End</Btn>
        </div>
      </Card>
    );
  }

  // ── RENDER: REST ──
  if (phase === "rest") {
    const nextStep = steps[stepIdx + 1];
    const isMidPullupSet = currentStep?.type === "pullup" && (currentStep.sets || 1) > setIdx + 1;
    return (
      <Card>
        <div style={{ fontSize: 11, color: C.muted, letterSpacing: 0.5, textTransform: "uppercase", marginBottom: 8 }}>
          Rest
        </div>
        <div style={{
          background: C.bg, border: `1px solid ${C.border}`,
          borderRadius: 12, padding: "20px 16px", marginBottom: 16,
          textAlign: "center",
        }}>
          <div style={{ fontSize: 56, fontWeight: 900, color: C.blue, lineHeight: 1, fontVariantNumeric: "tabular-nums" }}>
            {fmtSec(restRemaining)}
          </div>
          <div style={{ fontSize: 12, color: C.muted, marginTop: 6 }}>seconds remaining</div>
        </div>
        <div style={{ fontSize: 12, color: C.muted, marginBottom: 16, lineHeight: 1.5 }}>
          {isMidPullupSet ? (
            <>Next: <b style={{ color: C.text }}>set {setIdx + 2} of {currentStep.sets}</b>.</>
          ) : nextStep ? (
            <>Up next: <b style={{ color: C.text }}>{nextStep.title}</b> · {nextStep.intensityLabel}.</>
          ) : (
            <>Final step coming up.</>
          )}
        </div>
        <div style={{ display: "flex", gap: 10 }}>
          <Btn onClick={advanceFromRest} color={C.blue}>Skip rest</Btn>
          <div style={{ flex: 1 }} />
          <Btn onClick={onClose} color={C.border} small>End</Btn>
        </div>
      </Card>
    );
  }

  // ── RENDER: PULLUP ──
  if (phase === "pullup") {
    const setsTotal = currentStep.sets || 1;
    return (
      <Card>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline", marginBottom: 12 }}>
          <div style={{ fontSize: 11, color: C.muted, letterSpacing: 0.5, textTransform: "uppercase" }}>
            Step {stepIdx + 1} of {steps.length} · Set {setIdx + 1} of {setsTotal}
          </div>
          <div style={{ fontSize: 11, color: C.muted }}>BW {protocol.bodyWeightLbs} lbs</div>
        </div>
        <div style={{ fontSize: 22, fontWeight: 800, marginBottom: 10 }}>{currentStep.title}</div>
        <div style={{ fontSize: 12, color: C.muted, marginBottom: 16, lineHeight: 1.5 }}>
          {currentStep.description}
        </div>
        <div style={{
          background: C.bg, border: `1px solid ${C.border}`,
          borderRadius: 12, padding: "20px 16px", marginBottom: 16,
          textAlign: "center",
        }}>
          <div style={{ fontSize: 11, color: C.muted, letterSpacing: 0.5, textTransform: "uppercase", marginBottom: 6 }}>Reps</div>
          <div style={{
            fontSize: 64, fontWeight: 900,
            color: pullupReps >= currentStep.targetReps ? C.green : C.purple,
            lineHeight: 1, fontVariantNumeric: "tabular-nums",
          }}>
            {pullupReps}
          </div>
          <div style={{ fontSize: 12, color: C.muted, marginTop: 6 }}>
            target {currentStep.targetReps}
          </div>
          <div style={{ display: "flex", gap: 10, marginTop: 14, justifyContent: "center" }}>
            <Btn onClick={() => setPullupReps(r => Math.max(0, r - 1))} color={C.border} small>−</Btn>
            <Btn onClick={() => setPullupReps(r => r + 1)} color={C.green}>+1 rep</Btn>
          </div>
        </div>
        <div style={{ display: "flex", gap: 10 }}>
          <Btn onClick={completePullupSet} color={C.blue}>
            {setIdx + 1 < setsTotal ? "Set done" : "Done"}
          </Btn>
          <Btn onClick={skipStep} color={C.border} small>Skip</Btn>
          <div style={{ flex: 1 }} />
          <Btn onClick={onClose} color={C.border} small>End</Btn>
        </div>
      </Card>
    );
  }

  // ── RENDER: DONE ──
  if (phase === "done") {
    return (
      <Card>
        <div style={{ fontSize: 22, fontWeight: 800, marginBottom: 8, color: C.green }}>
          ✓ Warm-up complete
        </div>
        <div style={{ fontSize: 13, color: C.text, lineHeight: 1.6, marginBottom: 16 }}>
          Forearms primed, fingers awake, neither flash-pumped nor under-cooked. The video calls for ~10 minutes of full rest now to clear fatigue, then you're ready for early goes.
        </div>
        <div style={{ fontSize: 12, color: C.muted, marginBottom: 16, lineHeight: 1.5, fontStyle: "italic" }}>
          Nothing here was logged — warm-up reps don't update the force curve.
        </div>
        <Btn onClick={onClose} color={C.green}>Close</Btn>
      </Card>
    );
  }

  return null;
}

export default WarmupView;
